### ISSUE TITLE
Does not support actionLayout in menu

### ISSUE THREAD

**Issue by samuelcai** [robolectric/robolectric#1290]
Version 2.3
We're using actionLayout in menu for the action view, not actionViewClass. And calling MenuItem.getActionView() return null.
By checking source code in ShadowMenuInflater, method addActionViewToItem, seems only actionViewClass is supported.

**Comment by mag** [comment]
I saw a colleague running into this problem today; I don't believe the workaround suggested will work. During visible(), the activity's onCreateOptionsMenu method is called, but ShadowMenuInflator just doesn't populate the MenuItem with an ActionView if 'actionLayout' is used rather than 'actionViewClass'. I'm hoping this works on Robolectric 3.0, though, per #1446.

@erd, if you like feel free to  re-open this...but I think "won't fix" is also reasonable since 3.0 is imminent.
