### ISSUE TITLE
Tests with timeout have different behaviour

### ISSUE THREAD

**Issue by Glamdring** [robolectric/robolectric#1407]
Whenever I add timeout=xxx to a @Test annotation, the behaviour is different. In one instance my test failed with timeout if I set a timeout, but completes immediately (long before the timeout would be reached) if I don't. 

I took a look at the code of Robolectric runner and noticed it doesn't have specific code for handling the timeout. The stacktrace inside timeout=... my method includes only core JUnit classes and no robolectric classes, which leads me to believe that robolectric is not invoked when there is a timeout.

Could you investigate that?

**Comment by jaredsburrows** [comment]
@Glamdring Are you still seeing this in Robolectric 3.0-rc3?

**Comment by kriegfrj** [comment]
I've recently hit this issue while working on the scheduling code, and I've figured out the problem. In a nutshell: there are several places in Robolectric where we make the assumption that test setup thread == test execution thread == Robolectric's UI/main looper thread. When you use the `timeout` setting in JUnit, the main test thread (on which all the setup is run) spawns a background thread on which to execute the test, so that the execution thread is no longer the same as the setup thread. This violates the assumption and causes things to break in subtle ways - Roblectric actually sets up the main looper on the test `setup` thread, so you end up with test code running on a thread which is *not* the main looper thread (contrary to what all of Robolectric's code assumes).

I hit this when I tried to fix a problem with `ShadowLooper.myLooper()` - it would automatically create & return a new looper for the current thread even if `prepare()` had not yet been called. In real Android this is not permitted & so this might mask bugs in your code, so I fixed it. However, this means that if you use `timeout` your test will be running in a thread that doesn't have a looper. This caused one of the tests in ShadowValueAnimatorTest (which uses a timeout) to fail with an "AndroidRuntimeException: must be run on a thread with a looper" or something like that. I could roll back the change to `ShadowLooper` as a workaround for this particular case, but I'd imagine that there are dozens of other ways in which having this assumption violated might have interesting side effects aside from this particular example, so that wouldn't be a general fix.

I think that there might be a way to fix this so that `timeout` works as advertised, but I don't have time to work on it right now. In the meantime, the workaround is if you need timeout behaviour to roll your own - it's only a few lines of extra code per test (see `ShadowValueAnimatorTest.test_WhenInfiniteAnimationIsPlayed_AnimationIsOnlyPlayedOnce()` for an example).
