### ISSUE TITLE
GPL License in your dependencies

### ISSUE THREAD

**Issue by gdemiollis** [robolectric/robolectric#1414]
Hi,

I was checking the licences in my project using Robolectric and I discovered that you were using a library (vtd-xml) that has a GPL licence.
http://mvnrepository.com/artifact/com.ximpleware/vtd-xml/2.11.

Can you have a MIT license with a dependency on a GPL License?

Thank you for your answer.

Guilhem

**Comment by smdremedy** [comment]
Hi,
any news on the topic?

**Comment by jaredsburrows** [comment]
I do not see an issue here. Robolectric is already open source. Please see (https://en.wikipedia.org/wiki/GNU_General_Public_License)

> The GNU General Public License (GNU GPL or GPL) is the most widely used[6] free software license, which guarantees end users (individuals, organizations, companies) the freedoms to run, study, share (copy), and modify the software. Software that allows these rights is called free software and, if the software is copylefted, requires those rights to be retained. The GPL demands both. The license was originally written by Richard Stallman of the Free Software Foundation (FSF) for the GNU project.

> In other words, the GPL grants the recipients of a computer program the rights of the Free Software Definition[7] and uses copyleft to ensure the freedoms are preserved whenever the work is distributed, even when the work is changed or added to. The GPL is a copyleft license, which means that derived works can only be distributed under the same license terms. This is in distinction to permissive free software licenses, of which the BSD licenses and the MIT License are the standard examples. GPL was the first copyleft license for general use.

**Comment by emartynov** [comment]
Jared, did you read this?

>The GPL is a copyleft license, which means that derived works can only be distributed under the same >license terms.

**Comment by jaredsburrows** [comment]
@emartynov Robolectric is currently not GPL'ed but it is open source.

**Comment by emartynov** [comment]
Ah, you mean that is not our problem but Robolectric problem. Robolectric is using GPL dependency but itself distributed over commercial friendly licence. Thanks for explanation!

**Comment by jaredsburrows** [comment]
It is not really anyones problem. Even if you changed Robolectric to use the GPL license, it wouldnt affect anything. It would only affect those that "fork" Robolectric really. They would also have to use GPL.

**Comment by jaredsburrows** [comment]
@emartynov @erd A really good read: http://programmers.stackexchange.com/a/47048/51487.

**Comment by sumio** [comment]
If the license of Robolectric becomes GPL, a test code using Robolectric must be released under GPL.
So, a product code linking the test code must be distributed under GPL.
Of course, only the product code (without test code) can be distributed under any Licenses.

It is no problem in case of developing proprietary software because the product code will be released _without_ the GPL-ed (using Robolectric) test code.

However, open-source software licensed under non-GPL (e.g. Apache License) and distributed with a test code using Robolectric may become a problem. 
The developers have only the following alternatives which would be unacceptable:

- They change the license of their software to GPL.
- They hide  (not to be public) their test code using Robolectric.

Would you remove GPL-ed dependency and use an alternative XML parser?

**Comment by xian** [comment]
Robolectric 3.3.2 is now GPL-free!

**Comment by YousefED** [comment]
Hi @xian ,

We recently scanned for GPL files, and came across this file (ServiceFinder.java) https://github.com/robolectric/robolectric/blob/7697d1217c5eb0dee454004efe60ba219f398255/utils/src/main/java/org/robolectric/util/inject/ServiceFinder.java which seems to be GPL licensed as well. Are you sure this should be shipped with  robolectric?

**Comment by hoisie** [comment]
@YousefED thanks for pointing this out. I am clueless when it comes to matters of software licensing, so I will try to reach out to someone more knowledgeable for guidance.

Can you explain your situation a little more? Are you shipping out code that has a dependency on Robolectric code, or binaries that link against Robolectric?

**Comment by hoisie** [comment]
FYI @YousefED I have a change coming soon that will remove this file from the sources.

I am not a licensing expert, but https://github.com/robolectric/robolectric/issues/1414#issuecomment-187713042 sounds reasonable to me. Unless you are shipping test code, I am struggling to see how this is an issue. EIther way, that ServiceFinder will be removed shortly :)

**Comment by YousefED** [comment]
> FYI @YousefED I have a change coming soon that will remove this file from the sources.
> 
> I am not a licensing expert, but [#1414 (comment)](https://github.com/robolectric/robolectric/issues/1414#issuecomment-187713042) sounds reasonable to me. Unless you are shipping test code, I am struggling to see how this is an issue. EIther way, that ServiceFinder will be removed shortly :)

Great, thanks! You're right that I think it normally shouldn't be an issue indeed, because users won't ship the test code (not a lawyer though).

However, I think technically you can't use the MIT license for your project as long as it contains the GPL file (the licenses are incompatible that way).

Great that it's being resolved this quickly, thanks!
