### ISSUE TITLE
How to mock activity class fields that get initialized in onCreate()

### ISSUE THREAD

**Issue by athkalia** [robolectric/robolectric#1529]
Hello,

I am wondering if there is a way to initialize an activity, without calling the onCreate() method, then set some mocks on that activity, and only after that carry on with the onCreate() method.
The reason I am asking this is because I have a couple of database calls in the onCreate() method that I want to mock, but when I use the 

MyActivity activity = Robolectric.buildActivity(MyActivity.class).create().get(); the onCreate() method has already been executed, before I have a chance to add mocks in the activity to stop the database calls from running

**Comment by erd** [comment]
What I typically do is use Dagger to define a set of injector bindings for a particular test. You can set up the bindings before you call `setupActivity` and the activity will go through it's normal startup sequence with the mocks that you have defined.

**Comment by niccs** [comment]
@erd  do you have some reference or example for the same!!!  I am using robolectric 3.0 to test my activity and I want to mock a utility class defined inside the activity. The problem is very similar to this post:--

http://stackoverflow.com/questions/32707894/robolectric-3-0-mockito-how-to-mock-a-class-inside-activity

**Comment by jongerrish** [comment]
How do you get your dependencies in your production app?

You'l need a way to provide mocks instead.

Most people use a service locator or dependency injection, you'll want to
replace this with something that provides mocks instead.

If you provide dependencies by an android.app.Application subclass as your
service locator then you can specify @Config(application =
MyMockApplication.class) rather than your production application.
