### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by ronshapiro** [robolectric/robolectric#1569]
As I've used Robolectric more and more, I find that a lot of the methods lack documentation and aren't as obvious as they may seem. I'm down to work on adding Javadoc to a lot of it, but I want to make sure others are interested in making an effort to adding it to new code (and help making a pass and adding it in). Is there a good way to track buy-in?

**Comment by erd** [comment]
The high-level docs at robolectric.org live in the `robolectric/robolectric.github.io` repo. Contributions are always welcome. I'm going to work on updating those when 3.0 is released, but as with all documentation efforts, it is low on the priority list.

With respect to robolectric itself, classes that are in the public API (i.e. things outside of org.robolectric.internal) should have docs associated with them. I'd like to avoid documenting @Implementation methods, since those should match the semantics of the underlying Android method. If they need to be documented, it's a smell. One thing that would be nice is to have good class-level docs for shadows that show how they are intended to be used, especially for shadows that have very fake implementations.

**Comment by jaredsburrows** [comment]
@ronshapiro  @erd Today I have spent some time cleaning up and adding to the `2.4 to 3.0` wiki: https://github.com/robolectric/robolectric/wiki/2.4-to-3.0-Upgrade-Guide-(Draft).

Other than that I use StackOverflow and view the Robolectric tests in this repository.

**Comment by ronshapiro** [comment]
You shouldn't need to look at tests to understand what code should be doing. While I wouldn't want to duplicate documentation for `@Implementation` methods, I think it's very useful within an IDE to get that information right away. An `{@link}` to simplify that process would be great, or even better it would be cool if we found a way in the build process to inject the corresponding `@Implementation`s javadoc into the Robolectric jar. That way code wouldn't get messy but still have the same end-user benefit.

**Comment by jaredsburrows** [comment]
I completely agree. @erd  said "Contributions are always welcome.". I contribute to the docs as I upgrade my projects from 2.4 to 3.0,
