### ISSUE TITLE
Activity Controller restart() executes start step

### ISSUE THREAD

**Issue by mehmetf** [robolectric/robolectric#1640]
This page http://robolectric.org/activity-lifecycle/ implies that controller methods simulate activity lifecycle exactly. According to Android docs, restart() step should be followed by start() step. However, the following code: controller.restart().start().resume(); ends up calling onStart() twice which can cause issues. For now I am changing this to 

controller.restart().resume();

but I am not sure if this has any side effects.

**Comment by kriegfrj** [comment]
I think that this is by design, and `controller.restart().resume()` is thus the correct way to invoke it.

The `ActivityController` methods simply call the corresponding methods in the real Android code in `Activity`. So it behaves this way because that's how Android behaves: `ActivityController.restart()` simply calls the package-private method `Activity.performRestart()`, which in turn calls `onRestart()`, but also calls `performStart()` (which in turn calls `onStart()`). 

In fact, looking at the code in `Activity.performResume()`, it seems that if you simply called `controller.resume()` without calling `restart()`, then the call to `Activity.performResume()` will end up calling `onRestart()` and `onStart()` for you (whether you wanted it to or not).

**Comment by mehmetf** [comment]
Thanks for the clarification. I suppose an update to robolectric docs to clear this up would be helpful. Other than that, not much can be done.

**Comment by mehmetf** [comment]
Thanks for the clarification. I suppose an update to robolectric docs to clear this up would be helpful. Other than that, not much can be done.

**Comment by mehmetf** [comment]
Thanks for the clarification. I suppose an update to robolectric docs to clear this up would be helpful. Other than that, not much can be done.
