### ISSUE TITLE
onLoadFinished receives a null cursor

### ISSUE THREAD

**Issue by nolanlawson** [robolectric/robolectric#1664]
(3.0-snapshot) If you try to load thumbnails from the gallery, then Robolectric throws an exception.

I have [a sample app](https://github.com/nolanlawson/demo-robolectric-1664) to demonstrate. Note that, when you run the app on a phone, it shows "thumbnail load finished. Count: (number of photos you have)."

When you run the Robolectric tests, though, you get a NullPointerException:

```
java.lang.NullPointerException
	at com.nolanlawson.robolectric.foo.MainActivity.onLoadFinished(MainActivity.java:68)
```

**Comment by nolanlawson** [comment]
To run the test:

```
git clone git@github.com:nolanlawson/demo-robolectric-1664.git
cd demo-robolectric-1664
./gradlew test
```

**Comment by erd** [comment]
I suspect that you are getting a null `Cursor` because you are querying the `MediaStore` tables which do not exist in Robolectric. I verified that `AsyncTaskLoader` is correctly passing the value from `loadInBackground` to `deliverResult` so if you did have a result from the query, it should be handled by the loader.

**Comment by nolanlawson** [comment]
So what is the recommended fix for this? To detect that we're in a Robolectric environment and return an empty list? Something else?

**Comment by erd** [comment]
I would probably wrap the cursor creation in a class that you control (`MediaCursorFactory` or something) and use Dagger to inject a mock in the test that returns a cursor with the data you'd expect to get from the query.
