### ISSUE TITLE
Bitmap should not override equals()

### ISSUE THREAD

**Issue by aberent** [robolectric/robolectric#1684]
The Android bitmap class does not override equals(), so two Android bitmaps are only equal if they are the same object. The Robolectric ShadowBitmap class does, however, override equals() to compare equal if two bitmaps have the same height, width, and description. As a result, the following test incorrectly fails:

    @Test
    public void testBitmap() {
        Bitmap.Config conf = Bitmap.Config.ARGB_8888;
        int c[] = new int[]{Color.RED};
        Bitmap bmp1 = Bitmap.createBitmap(c, 1, 1, conf);
        c[0] = Color.GREEN;
        Bitmap bmp2 = Bitmap.createBitmap(c, 1,1, conf);
        assertFalse(bmp1.equals(bmp2));
    }

**Comment by sweetleon** [comment]
:-1: This breaks tests for existing software. Android may not need to understand bitmap equivalence, but tests often do.

**Comment by erd** [comment]
Almost every change will break something for somebody somewhere. You can still use `getCreatedFromPath`, `getCreatedFromResId`, and / or `getCreatedFromBitmap` to check that your test got the correct bitmap.

**Comment by sweetleon** [comment]
That's exactly what ShadowBitmap.equals should do to maintain compatibility
with existing test code. :)

On Friday, May 22, 2015, Erich Douglass <notifications@github.com> wrote:

> Almost every change will break something for somebody somewhere. You can
> still use getCreatedFromPath, getCreatedFromResId, and / or
> getCreatedFromBitmap to check that your test got the correct bitmap.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/robolectric/robolectric/issues/1684#issuecomment-104786905>
> .
>


-- 
--
Snet form a tiny keybord

**Comment by aberent** [comment]
The point of Robolectric is to unit test Android code. The problem is that,
before this bug was fixed, if your Android code under test (not your test
code) used Bitmap.equals, them it behaved differently depending whether it
was passed an Android Bitmap or a ShadowBitmap. As such tests of such code
gave the wrong results.

**Comment by sweetleon** [comment]
Why would anyone's Android code use `Bitmap.equals` when, as @aberent correctly pointed out, it's unimplemented and therefore functionally the same as `==` (and a touch slower)?

OTOH, there's plenty of Robolectric code that relies on `ShadowBitmap.equals`, imperfect tho it was, bc it solves the testing problem better than the alternative methods @erd pointed out. I say "better" bc it's less verbose and doesn't require `ArgumentCaptor` so it can be a 1-line call to `verify` rather than 3 lines. Compare the following:
`verify(dependency).callWithBitmapArg(expectedBitmap);`
vs.
`ArgumentCaptor<Bitmap> bitmapArgCaptor = ArgumentCaptor.forClass(Bitmap.class);
verify(dependency).callWithBitmapArg(bitmapArgCaptor.capture);
assertThat(shadowOf(bitmapArgCaptor.getValue()).getCreatedFromResId())).isEqualTo(expectedResId);
`

Even if it weren't more elegant, there's value in maintaining backwards compatibility and not making the entire community spend time rewriting tests. 

But the bug in `ShadowBitmap.equals` should definitely be fixed.

**Comment by aberent** [comment]
At a guess, the original writer didn't realize that it wasn't overridden.
