### ISSUE TITLE
ShadowMessageQueue and/or Scheduler doesn't dispatch Messages(Runnables) under certain circumstances

### ISSUE THREAD

**Issue by laminina** [robolectric/robolectric#1711]
I'm in process of migrating from 2.4 to 3 and noticed this 'very' visible change.

It seems that now when having nested runnables/handlers running in the UI thread, their messages are not being dispatched by the ShadowMessageQueue anymore. The 'nested' behavior can be described below.. environment (We use AsyncTask, handlers created in the Lopper.getMainLopper(), We use Otto that we posts events in a handler running in the MainLooper too). 

The ui gets triggered by a performClick
alertDialog.getButton(AlertDialog.BUTTON_POSITIVE).performClick();
An alertDialog in the positive click listener triggers:
an AsyncTask#doInBackground that eventually triggers
a) handler that posts a Runnable (no delay) -> that also posts to Otto inside that runnable
b) an otto event that eventually has a handler that post a runnable

the otto events that in the runnable a) don't get executed at all...The only way to get them dispatched is by doing:
        ShadowLooper.getUiThreadScheduler().pause();
alertDialog.getButton(AlertDialog.BUTTON_POSITIVE).performClick();
        ShadowLooper.getUiThreadScheduler().unPause();

As you can see to perform the migration in the whole project will be very painful because there are a lot places that run under this environment.

To isolate the problem I created the same environment using AsyncTask and handlers, and I was able to reproduce it:

This is the asyncTask

    public class TempAsyncTask extends AsyncTask<Object, Object, Void> {

    public static boolean doInBackGroundCalled = false;
    public static boolean doInBackGroundHandlerCalled = false;
    public static boolean doInBackGroundHandlerCalled2 = false;
	public TempAsyncTask() {}

    @Override
    protected Void doInBackground(Object... objects) {

        new Handler(Looper.getMainLooper()).post(new Runnable() {
            @Override
            public void run() {

                doInBackGroundHandlerCalled = true;

                new Handler(Looper.getMainLooper()).post(new Runnable() {
                    @Override
                    public void run() {
                        doInBackGroundHandlerCalled2 = true;

                    }
                });

            }
        });
        doInBackGroundCalled = true;

		return null;
	}
    }

This is the main block of the unitTest
  // verify positive button click
        //ShadowLooper.getUiThreadScheduler().pause();
        alertDialog.getButton(AlertDialog.BUTTON_POSITIVE).performClick();
      //  ShadowLooper.getUiThreadScheduler().unPause();
        assertTrue(TempAsyncTask.doInBackGroundCalled);
        assertTrue(TempAsyncTask.doInBackGroundHandlerCalled);

This is the dialog part, that is just calling the asyncTask

    public static void showDialogAndClick(final Activity activity) {

        new AlertDialog.Builder(activity)
                .setTitle("Show Dialog")
                .setMessage(R.string.dialog_message)
                .setCancelable(true)
                .setPositiveButton(R.string.dialog_ok, new DialogInterface.OnClickListener() {
                    public void onClick(DialogInterface dialog, int whichButton) {

                        new TempAsyncTask().execute();

                    }
                })
                .show();
    }

As soon as I uncomment the pause/unpause the assertions passed.
I tried to debug the ShadowMessageQueue and Scheduler, so far no luck when debugging enqueueMessage's Runnable. Any hint will be appreciated.

**Comment by kriegfrj** [comment]
Hi @laminina, I haven't looked into your problem specifically or in detail, but I know that the major change from 2.4 to 3.0 in message handling was #1431 & #1466. The main issue that this PR was meant to fix was that two Handlers attached to the same Looper could (in some circumstances) affect each other's queues, which should not happen. I can't see anything in your code that should be affected by this change though.

Also check out #1306, which might be related to your problem.

I'd like to offer to try and have a further look but I'm extremely busy at the moment, so I'll try but I can't guarantee anything, sorry.

**Comment by laminina** [comment]
Thanks @kriegfrj 

So I spent all day in this trying to debug, I noticed in my example I had an Asynctask which was making my debugging more complicated managing 2 Schedulers (mainLooper, vs the other Looper). 

So I simplified with this"
  public static boolean doInBackGroundCalled = false;
    public static boolean doInBackGroundHandlerCalled = false;
    public static boolean doInBackGroundHandlerCalled2 = false;

    public static void promptForSignOut(final Activity activity) {

        new AlertDialog.Builder(activity)
                .setTitle("Signout")
                .setMessage(R.string.signout_message)
                .setCancelable(true)
                .setPositiveButton(R.string.signout, new DialogInterface.OnClickListener() {
                    public void onClick(DialogInterface dialog, int whichButton) {

                        doInBackGroundCalled = true;

                        new Handler(Looper.getMainLooper()).post(new Runnable() {
                            @Override
                            public void run() {

                                doInBackGroundHandlerCalled = true;

                                new Handler(Looper.getMainLooper()).post(new Runnable() {
                                    @Override
                                    public void run() {
                                        doInBackGroundHandlerCalled2 = true;
                                    }
                                });
                            }
                        });
                    }
                })
                .show();
    }

And the doInBackGroundHandlerCalled and doInBackGroundHandlerCalled2 are not yet called (we already knew this).

I took a closer look at the ShadowMessageQueue when we enqueueMessages  and the Scheduler that hold to a list of Runnables, from what I understood while we are running a Runnable the Scheduler has the flag isExecutingRunnable = true, and while that is true it will queue and sort the runnables. Once that flag is set to false, I see that AlertDialog unpauses, or even ActivityController that unpauses (I've seen that this is expected because those run on post pause behavior) and the scheduler will advanceToLastPostedRunnable, this is fine. 

But there is a point when a callback is executed (the callback set in the ShadowMessageQueue) it's the head, then we set n to be the head, the message is dispatched, the runnable gets removed from the scheduler (that sometimes is not even there anymore) and there is no one who can proceed with the messageQueue to continue executing the LinkedList: And the scheduler is still holding to a list of runnable including the first Handler I added and that's why the handler's runnable is not even executed to continue.

    Message n = shadowOf(m).getNext();
            if (m == msg) {
              setHead(n);
              dispatchMessage(msg);
              return;
            }


I know I'm not proposing any solution, but you know more than me about this code. The linkedlist is there ready to be triggered, as I said before doing unpause will fix it, but I cannot add this everywhere in our project. considering that we have this nested behavior. I'll try to look for a workaround in the mean time, but hopefully we can get to the bottom of this :). Unless it becomes a Robolectric pattern that we need to call pause/unpause everytime we have this nested handlers/runnables.

I'll give a 3rd round tomorrow thanks for reading.

**Comment by laminina** [comment]
This ugly shadow seems to do the trick :(

@Implements(value = Handler.class, inheritImplementationMethods = true )
public class HandlerShadow extends ShadowHandler {

    @Implementation
    public boolean post(Runnable r) {
        r.run();
        return true;
    }
}

**Comment by kriegfrj** [comment]
I can see how that would do the trick, but that of course also circumvents the scheduling code altogether.

I've set aside some time now so I'll have a quick look and see if I can figure out what's going on.

**Comment by kriegfrj** [comment]
> Unless it becomes a Robolectric pattern that we need to call pause/unpause everytime we have this 
> nested handlers/runnables.

My intention was that #1466 should be entirely backward-compatible, apart from fixing the cross-handler pollution issues that I was facing - so if it is forcing a change of design pattern I'd consider that a failure in my implementation that needs fixing (preferably before 3.0 is released).

I had a bit of a look at this today during my lunch break and thanks to your extensive notes I think I managed to reproduce your problem. I was able to simplify it to a case that uses only nested `Handler`s and the main looper. It seems that even when the scheduler is not paused, posted `Runnable`s don't run immediately as you'd expect (your hack forces them to run immediately, but also means you can't control the events schedule). Pausing and then unpausing runs all of the pending tasks.

Having been able to simplify it to this extent I should be able to figure out what's going on later tonight and hopefully have a PR ready to fix it by the time you start tomorrow.

**Comment by laminina** [comment]
This is pretty good news, thanks for the help, :)

**Comment by kriegfrj** [comment]
I didn't get as much time at this as I'd have liked, but I did manage to discover that it's the `unPause()` call after the post that fixes it, regardless of whether or not you call `pause()` beforehand. `unPause()` contains a call to `advanceToLastPostedRunnable()`, which is why cause `unPause()` causes them all to run. So the question is why don't they run without manual intervention - expected behaviour is that if the scheduler is not paused then all posts should run immediately (especially posts that are not delayed).

I also discovered that there were some other changes to `Scheduler` in Feburary (7900d4b225891bf5e98601d7060b72f9fc5667f8), but managed to confirm that this bug existed before those changes, so it probably was #1466 that did it.

Will try and have a look a bit later - it's probably a simple fix (the trick is finding it!)

**Comment by erd** [comment]
Thanks for taking a look at this @kriegfrj !

**Comment by kriegfrj** [comment]
Hmmm, the plot thickens...

After some digging, I managed to discover that @laminina's observed behaviour had nothing to do with my changes in #1466. It seems this behaviour was by design, part of a change to `Scheduler` that was part of #1351 (designed to fix #919). I know it was by design because there are two methods in `SchedulerTest` that explicitly test for this behaviour with nested calls to `postDelayed()`:

*  `postDelayed_whenAnotherPostDelayedIsEnqueued_runsInCorrectSequence()` runs `unPause()` first, and then enqueues the outer runnable. It expects that the inner `Runnable` *isn't* run.
* `postDelayed_whenAnotherPostDelayedIsEnqueued_runsInCorrectSequence2()`, on the other hand, posts the outer runnable first and *then* runs `unPause()`. It expects the inner `Runnable` to run.

Given that it seems to have been designed this way I'd like to get input from @ry4n1m3 before making a decision on how to proceed here, however I think I agree with @laminina that this represents an inconvenient departure from 2.4 behaviour, and I think we can still get the best of #1351's fix for #919 without losing the convenience of the 2.4 behaviour that @laminina (and probably dozens of others) have come to depend on. My understanding of the paused/unpaused state in the scheduler is that if the scheduler is unpaused, then any event posted at the current time (or earlier) should execute immediately without manual intervention (at least, that's what the code in `Scheduler.postDelayed()` would seem to imply). So my proposed fix would be that `runOrQueueRunnable()` should call `advanceBy(0)` after it executes a runnable if it is either unpaused or set to idle constantly. I'll submit a PR for this shortly and invite comment from @erd, @laminina and @ry4n1m3.
