### ISSUE TITLE
Difference between Robolectric's getBackgroundThreadScheduler() and ShadowApplication's getBackgroundScheduler()

### ISSUE THREAD

**Issue by laminina** [robolectric/robolectric#1758]
Not sure if it's an issue or more of a guideline question.

It seems that Robolectric#getBackgroundThreadScheduler and Robolectric#getForegroundThreadScheduler point to the same Scheduler meaning the mainLopper's Scheduler.

It also seems the ShadowApplication.getInstance().getBackgroundScheduler() is another scheduler that is a member class of the ShadowApplication.

I just noticed this because I was manually pausing Robolectric.getBackgroundThreadScheduler().pause(); to avoid an AsyncTask to be executed with no luck. Because the ShadowAsyncTask in the execute calls the ShadowApplication#BackgroundScheduler to post the runnable.

I can start calling ShadowApplication.getInstance().getBackgroundScheduler().pause()/unpause() that's not a problem, but I just would like to point out that there might be a discrepancy here.

If you think this should be fixed, I can fix it, just want to double check with your guys, thanks! :)

**Comment by erd** [comment]
Yeah, there's a bug here. I've got a PR in flight that should address it.

**Comment by 1zaman** [comment]
Why is the background scheduler using the same thread as the foreground scheduler? The `Scheduler` implementation is also inconsistent with the `Handler` implementation, in that the `post()` method seems to run the `Runnable` immediately if called from it's associated thread, while `Handler` schedules it to be processed _after_ the current execution is complete. Also, it doesn't seem to implement any synchronization. I am not sure why `MessageQueue` and `Looper` have been basically replaced with `Scheduler`, as it seems like it would be better to just implement any additional features into `ShadowLooper` instead of trying to implement it separately.

**Comment by 1zaman** [comment]
Also, the base `execute()` of `AsyncTask` has been shadowed to use the background scheduler, apparently without regard to whether `SERIAL_EXECUTOR` or `THREAD_POOL_EXECUTOR` is being used. This would cause the tests to behave differently than the actual application.

**Comment by 1zaman** [comment]
OK, so after reading #1879, it seems that muti-threading code is intentionally not supported, and is meant so be manually simulated in a serialized manner.
