### ISSUE TITLE
No Class def found error.

### ISSUE THREAD

**Issue by hronik1** [robolectric/robolectric#1806]
Exception in thread "main" java.lang.NoClassDefFoundError: junit/textui/ResultPrinter
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:191)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:122)
Caused by: java.lang.ClassNotFoundException: junit.textui.ResultPrinter
...

Above error when attempting to run tests.
Target api version 21, using android studio 1.2 and added below test dependencies in the build.gradle:
    testCompile 'junit:junit:4.12'
    testCompile "org.mockito:mockito-core:1.9.5"
    testCompile "org.robolectric:robolectric:3.0-rc2"

**Comment by kageiit** [comment]
try running the test again in android studio. this issue seems to crop up rarely

**Comment by jaredsburrows** [comment]
Show some code, example test and are you running via command line or the ide?

**Comment by erd** [comment]
If this is an Android Studio issue, there's probably not much we can do.

**Comment by andymstone** [comment]
I think there is definitely something odd going on when running Robolectric tests from Android Studio.  There are two options in Android Studio for running unit tests - using JUnit or using Gradle.  I find that one method works and one method doesn't, but the method that works seems to change at random.  Sometimes JUnit works, sometimes Gradle.  The working method can change even when I haven't modified my code.  I think it's somehow related either to cleaning the project or to restarting Android Studio, so I suspect it is some quite of weird path issue.

The tests always work from the command line and running a non-Robolectric test class always works from within Android Studio.

There are references on the Android Studio issues list to this type of problem, e.g. https://code.google.com/p/android/issues/detail?id=160024 and http://code.google.com/p/android/issues/detail?id=159840.  Based on that first link, the Android Studio folks seem to think it is a Robolectric problem (since it only happens with Robolectric tests), but I suppose the Robolectric folks probably think it is an Android Studio problem (since it only happens with Android Studio).

Anyway, the solution for me is to delete all of my run configurations when this happens and switch to using the other test runner!

Sorry, can't tell you exactly how to reproduce it because I can't make it happen consistently.

**Comment by mag** [comment]
I've seen that junit/textui/ResultPrinter problem before.  But I haven't
seen it in a while. What version of Android Studio are you running?

IIRC,  for me it happened when syncing the gradle project. Maybe you can
resync when you see it?

Mike

**Comment by erd** [comment]
Since this is not immediately reproducible, I'm going to close. Let me know if there is a way to reproduce and I'll re-open.
