### ISSUE TITLE
HttpFake Not Found

### ISSUE THREAD

**Issue by joanlopez** [robolectric/robolectric#1858]
Hi,

I wanna make my tests with HTTP Requests & Responses. 

I've seen that there was a Robolectric.httpRequestWasMade method that after was moved to a FakeHttp class in shadow, but I can't find it.

How I have to do it?

I'm working with RC.

Thanks.

**Comment by erd** [comment]
The method moved to `FakeHttp.httpRequestWasMade`

https://github.com/robolectric/robolectric/blob/master/robolectric-shadows/shadows-httpclient/src/main/java/org/robolectric/shadows/FakeHttp.java#L70-77

**Comment by mag** [comment]
Just a quick shout out for Square's [MockWebServer](https://github.com/square/okhttp/tree/master/mockwebserver) library, which is slightly misnamed as it is in fact a very real, programmable web server that happens to be very useful in tests.

It's great because it is not dependent on which HTTP library you use, unlike the Robolectric FakeHttp stuff, which only works for apache httpclient (IIRC).  So you could change everything about your stack and your tests would still run. It is also very fast and very flexible.

**Comment by erd** [comment]
Agreed @mag
