### ISSUE TITLE
NetworkOnMainThreadException not threw

### ISSUE THREAD

**Issue by FouadWahabi** [robolectric/robolectric#1919]
I performed some network operations on main thread so what was expected when running test is that an exception NetworkOnMainThreadException should be threw but every woks fine. So what's the problem ?

**Comment by jaredsburrows** [comment]
Honestly, I do not think this is an issue. It seems like you are **trying** to test Robolectric instead of using Robolectric to **test** you application.

Doing any network task on the UI thread will cause cause that run time exception: `NetworkOnMainThreadException`. You should run your code in another thread.

**Comment by FouadWahabi** [comment]
Firstly, I read the wiki and I know perfectly how to report an issue, and your job here is not to show me how.
Secondly, I'm not asking what's causing the `NetworkOnMainThreadException` so try to respond on the question or keep quite.

Thirdly, **This is the problem** the application **shouldn't be able to run with a network task on the main thread** but when using Robolectric every works fine and test succeeds and no Exception is thrown.

**Comment by jaredsburrows** [comment]
> and your job here is not to show me how.

Please not get upset. I am just trying to help you by getting more information.

Yes, in theory it should not be able to run but Roboletric trys emulates Android by running unit tests on the JVM.

**Comment by FouadWahabi** [comment]
I'm not upset.
I know that Roboletric tries to emulate Android by running unit tests on the JVM, but why all other exceptions works fine only with the `NetworkOnMainThreadException` it gets ignored, you don't think that it seems there's a problem with the `StrictMode` in the Robolectric android.jar library ?

**Comment by jaredsburrows** [comment]
Yes there may be an issue but I do not understand why you would want to test something that does not work naturally on Android. You are going to have to turn `StrictMode` off or wrap your code in a thread. I think you should use Robolectric to that that implementation.

**Comment by FouadWahabi** [comment]
It wasn't deliberate, I was testing a new library for network operations, but after succeeding all tests and finishing coding hoping it works perfectly, unfortunately, when I run the app on the device every thing gets wrong , and the problem was the library wasn't well documented so I called some methods on the main thread that it shouldn't be.

**Comment by mag** [comment]
I think the OP's complaint is that Robolectric is not accurately simulating
Android because it doesn't throw the exception when his code is doing
something wrong.

This is a problem that I've seen trip up a lot of developers who are new to
Robolectric. Unfortunately, in Robolectric the Android platform is not
operating as per normal. Robolectric has taken over the Loopers and only
one thread ever runs. So in terms of Thread.current, you are always going
to be on the Main thread. So this type of checking must be turned off.

I don't know how to get Robolectric to become more realistic, though I'd
love to get there somehow. It is too bad that by default, these types of
errors are not caught.

However, the workaround is to "pause" the main and background loopers, so
that you can control them in your tests. Then you can run the main thread
code and make sure that the network code doesn't happen until you invoke
the Loopers manually in your test. This ensures that the effects of your
code are only observed when the correct Looper has executed.  This approach
involves writing "negative" assertions, which is gross, but if you are
disciplined about the positive sides of the assertions (after the looper
has been allowed to run) then you can write meaningful tests.

Mike

**Comment by jaredsburrows** [comment]
@mag Thanks for your comments. I know the OP complaint is that Robolectric did not catch it. I am simply saying that Robolectric can't test *everything*. Yes, I would try pausing the background loopers as I use this to test my `AsyncTask`s.

**Comment by erd** [comment]
> Firstly, I read the wiki and I know perfectly how to report an issue, and your job here is not to show me how. Secondly, I'm not asking what's causing the NetworkOnMainThreadException so try to respond on the question or keep quite.

@jaredsburrows was trying to help. If you can't use a more civil tone, please do not post here.

As @mag mentioned, things that run on background threads in Android run on a single thread in Robolectric. We do this to make tests more reliable and to avoid race conditions in tests. Unfortunately, this means that you will not be able to test this behavior with Robolectric.
