### ISSUE TITLE
RobolectricGradleTestRunner Unable to find resource ID

### ISSUE THREAD

**Issue by alexfu** [robolectric/robolectric#1954]
Although the GitHub page for [robolectric-gradle-plugin](https://github.com/robolectric/robolectric-gradle-plugin) states that 

> With the release of Robolectric 3.0, this plugin is no longer needed to run tests with Gradle.

I still find myself having to use this plugin with the **RobolectricTestRunner** and not the suggested **RobolectricGradleTestRunner** when using Robolectric 3.0.

I am running tests strictly from the command line (gradle wrapper).

My test fails with `android.content.res.Resources$NotFoundException: Unable to find resource ID #0x7f0701db`

What I find a bit strange (maybe it's not) is that the stacktrace of this error has no reference to `RobolectricGradleTestRunner.class`, i.e.

```java
java.lang.RuntimeException: android.content.res.Resources$NotFoundException: Unable to find resource ID #0x7f0701db
	at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:244)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:188)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:54)
```

But in my tests I am clearly using it...

```java
@RunWith(RobolectricGradleTestRunner.class)
@Config(constants = BuildConfig.class, sdk = 21)
public class MyTest {
  ...
}
```

Have I mis-configured something?

**UPDATE**: After looking at `RobolectricGradleTestRunner`, it extends `RobolectricTestRunner` so my earlier point isn't so strange after all.

**Comment by andrewlord1990** [comment]
We had this problem when using RobolectricGradleTestRunner. However, the problem was:

1) We use Mac and so the working directory was the wrong location, which could be fixed by changing Run configurations Defaults -> JUnit working directory to $MODULE_DIR$ (this is described in the Robolectric setup guide)

2) We use different build variants that alter the application ID. The RobolectricGradleTestRunner uses the application ID for finding the R class (for resources). However, as our application ID is different to the package (due to the build variants changing it), it couldn't find the resources. The fix was setting the packageName in the @Config annotation.

**Comment by alexfu** [comment]
@andrewlord1990 thanks for the response. Both cases you outlined are exactly what I have. I'll try those solutions out.

**Comment by alexfu** [comment]
Solutions pointed out by @andrewlord1990 worked for me.

**Comment by jakub-g** [comment]
For people coming here from the future and using Android Studio 2.3: on top of changing *default run configuration* have `$MODULE_DIR$ ` as @andrewlord1990 suggests, you also need to *edit existing run configurations* 

See https://github.com/robolectric/robolectric/issues/2949#issuecomment-284439922

**Comment by pmdevacc** [comment]
This doesn't work for me. It still can't get the resource.

**Comment by slott** [comment]
Yeah - this is a bit joke. Having the exact same issue and I'm running the test from the command line like this:
./gradlew testDevDebugUnitTest --tests *.BasicRoboelectricTest

And the result is the same

 android.content.res.Resources$NotFoundException: Resource ID #0x7f020052

**Comment by calvarez-ov** [comment]
I was having this issue on the command line, using the android gradle plugin 3.0.0-beta6.
I found a solution here: #3169 : 
```gradle
android {
...
  testOptions {
    unitTests {
      includeAndroidResources = true
    }
  }
}
```

**Comment by AlienAsRoger** [comment]
I got an error with this as well. 

This solution:
```
    testOptions {
        unitTests {
            includeAndroidResources = true
        }
    }
```
Gives me that error:
```

Could not set unknown property 'includeAndroidResources' for object of type com.android.build.gradle.internal.dsl.TestOptions$UnitTestOptions. Open File
```

**Comment by fernando-barbosa** [comment]
I tried what @andrewlord1990 answered and did not work. Reading the others responses, I tried the answer of @calvarez-ov and it worked smooth as I wanted!

**Comment by DenisShov** [comment]
I has the same error as @AlienAsRoger has.

**Comment by PankajChunchun** [comment]
I was getting this error because I was using `@Config(manifest= Config.NONE)`. This was causing RobolectricGradleTestRunner to look resources into android or robolectric package (and offcource resources were not into these packages).

I removed it, and working now. Current working config is `@RunWith(RobolectricTestRunner.class)
@Config(constants = BuildConfig.class, sdk = 21)`
