### ISSUE TITLE
getMeasuredWidth() and getMeasuredHeight() not implemented for ShadowView

### ISSUE THREAD

**Issue by qmar** [robolectric/robolectric#2053]
I have stumbled upon a problem. The methods getMeasuredWidth() and getMeasuredHeight() were always returning 0. I have found out that there is no implementation for it.

I've found out that the implementation was there before. ([e.g. source for 1.1](http://grepcode.com/file/repo1.maven.org/maven2/com.pivotallabs/robolectric/1.1/com/xtremelabs/robolectric/shadows/ShadowView.java#ShadowView.getMeasuredWidth%28%29))

I am trying to understand why it was removed? I've tried to search the history but wasn't able to found an answer.

My solution is to extend the shadow and add the implementation. 
``````
@Implements(View.class)
public class ExtendedShadowView extends ShadowView {

	public int getMeasuredWidth() {
		return realView.getWidth();
	}

	public int getMeasuredHeight() {
		return realView.getHeight();
	}
}
```

```
@Config(constants = BuildConfig.class, sdk = 16, manifest = "./app/src/main/AndroidManifest.xml", shadows = ExtendedShadowView.class)
```

**Comment by erd** [comment]
Robolectric automatically delegates calls from the shadow to the shadowed object, which is why those methods were removed. The methods return zero because robolectric does not perform actual layout or drawing of views, so views never have a computed size.

There is some work going on in #1962 to implement real rendering, but it's not quite ready yet.
