### ISSUE TITLE
ShadowAlarmManager does not replace existing alarm with equal intents

### ISSUE THREAD

**Issue by kanelbulle** [robolectric/robolectric#2056]
Recently there was a change to ShadowAlarmManager where it was changed to "only remove an existing alarm if the trigger times are equal". However, the doc doesn't specify this behavior -- the doc says that an existing alarm will be replaced if the intents matches using filterEquals (and nothing else):
http://developer.android.com/reference/android/app/AlarmManager.html#set(int, long, android.app.PendingIntent)

So, the previous behavior was actually correct and matches the doc. The patch is therefore incorrect and should be reverted.

This is the patch mentioned above:
https://github.com/robolectric/robolectric/commit/971279e06eff78bf83f697e30892bbdeeb6b6be0

**Comment by erd** [comment]
Could you give me a test that I could run on a real device and on Robolectric to see that the behavior is different? I'm happy to revert if it is not correct.

**Comment by kanelbulle** [comment]
Sure, just to make sure I just tried this on a device:

```java
Intent intent = new Intent(context, TestReceiver.class);

AlarmManager alarmManager = (AlarmManager) context.getSystemService(Context.ALARM_SERVICE);
PendingIntent pendingIntent = PendingIntent.getBroadcast(context,
    0 /* request code */,
    intent,
    PendingIntent.FLAG_UPDATE_CURRENT);

alarmManager.set(AlarmManager.ELAPSED_REALTIME, 5000, pendingIntent);
alarmManager.set(AlarmManager.ELAPSED_REALTIME, 10000, pendingIntent);
```

And, like I interpret the documentation, I only receive a single broadcast.

Also, I think these two snippets in the doc for set(...) make it fairly clear:

> If there is already an alarm for this Intent scheduled (with the equality of two intents being defined by filterEquals(Intent)), then it will be removed and replaced by this one.

and

> If there is already an alarm scheduled for the same IntentSender, that previous alarm will first be canceled.

**Comment by DanDevine** [comment]
I don't think the original bug report is correct.  From the Android docs, the incoming Intent must match the filter test...AND the PendingIntent request code must match too, since that's what's being saved by the real AlarmManager.

```
Intent toLaunch = new Intent("com.foo.bar.AlarmReceiver.NOTIFICATION_EVENT");
PendingIntent pendingIntent = PendingIntent.getBroadcast(this, 1, toLaunch, PendingIntent.FLAG_ONE_SHOT);
alarmManager.setExact(AlarmManager.RTC_WAKEUP, alarmTime, pendingIntent);

toLaunch = new Intent("com.foo.bar.AlarmReceiver.NOTIFICATION_EVENT");
pendingIntent = PendingIntent.getBroadcast(this, 2, toLaunch, PendingIntent.FLAG_ONE_SHOT);
alarmManager.setExact(AlarmManager.RTC_WAKEUP, alarmTime, pendingIntent);
```

Assuming that the times are not identical, there should be 2 separate Alarm events in the queue due to the differing PendingIntent id's.   Please don't assume everyone just sets the Id field to 0.

I found this bug report, because my test isn't matching the real 'on-device' behavior.  When I set two distinct alarms on the device using the above code, I get two distinct events.  When checking the scheduled alarms with 3.0, I get only one....
