### ISSUE TITLE
Can't find AndroidManifest with Android Studio 1.4

### ISSUE THREAD

**Issue by scottdarch** [robolectric/robolectric#2070]
Robolectric 3.0 is looking under `build/intermediates/manifests/full/debug/AndroidManifest.xml` but Android Studio is putting them under `build/intermediates/manifests/androidTest/debug/AndroidManifest.xml`

I can't figure out how to work around this.

**Comment by erd** [comment]
That path contains `androidTest`. Did you select 'Unit Test' as the test artifact from the 'Build Variants' panel?

**Comment by legarspol** [comment]
With test artifact set to `Units Tests` mine is looking for the Android manifet in  build/intermediates/manifests/full/debug/AndroidManifest.xml and do not find it. Not sure if it's related tho.

**Comment by erd** [comment]
@scottdarch Which version of the android gradle plugin are you using?

**Comment by scottdarch** [comment]
1.3.0 and yes, I'm trying to build unit tests.

**Comment by legarspol** [comment]
1.2.3 on my side.

**Comment by jaredsburrows** [comment]
Which test runner are you using?

Which test runner to the run the tests from the IDE are you using?

Bare in mind, there is a difference from using the Gradle test runner and the Junit test runner from the IDE. There is also the `RobolectricTestRunner` and `RobolectricGradleTestRunner`.

**Comment by legarspol** [comment]
I succeed to solve that problem but I can't tell how I did.
My coworker had the project working well and I was running into many among this one. Then after rebuild, emptying cache I ended up deleting my workspace and checkout again and it made the tricks.
It may worth trying it.

**Comment by xtien** [comment]
I'm having the same issue. I made no changes in my project, I did upgrade Android Studio to 1.4.

**Comment by xtien** [comment]
In my TestRunner I override getAppManifest(Config config) like so:
 
`          if (FileFsFile.from(new String[]{"build/intermediates", "manifests"}).exists()) {
                manifest = FileFsFile.from(new String[]{"app/build/intermediates", "manifests", "full", flavor, type,
                        "AndroidManifest.xml"});
            } else {
                manifest = FileFsFile.from(new String[]{"app/build/intermediates", "manifests", "full", flavor, type,
                        "AndroidManifest.xml"});
            }
`

I changed the relative paths to absolute paths, now it works. Same happens in my unit tests: accessing a file via a relative path used to work, now I had to use the absolute path.

**Comment by paulrs** [comment]
I upgraded to Android Studio 1.4 this weekend and then let the app download all the other SDK/dev tool updates.  Our app's build.gradle file is configured with the following depency:

    testCompile "org.robolectric:robolectric:3.0"

Our test classes are annotated with

    @RunWith(RobolectricGradleTestRunner.class)

Prior to this upgrade, we were able to right click on any test class or test method and choose run, and Android studio would happily (albeit excruciatingly slowly) run all the `Test` annotated methods in the class or just an individual test method.  Since the 1.4 upgrade, we can right click and choose run and Android Studio will go through what looks like a normal compilation process with no errors generated, but then just nothing happens.  No tests are run, nada.  I've tried a number of different workarounds including removing the `RunWith` annotation altogether and changing the Run config to use the JDK 1.7 to see if it would run the tests as just pure Java, but the results are always the same: no compilation errors but nothing is run.

I'm not sure if this is tangentially related to the Manifest issue discussed above, but I would appreciate any advice anyone can offer about how to fix or even to troubleshoot what exactly is happening.

**Comment by paulrs** [comment]
After spending some time with one of my teammates who wasn't having this problem, we discovered that the fix to my issue involved changing the JUnit Defaults in the Run/Debug Configurations window to run a "Gradle-aware Make" Before launch.  I'm not sure exactly why that wasn't required before (or maybe it was).  What I discovered was that, once I had done at least one Gradle-aware Make, I could revert back to a regular Make as the Before launch task, and the unit tests ran properly again.  Hopefully, the recounting of this saga and its resolution for me will be useful to someone else should they encounter the same symptoms.

**Comment by ncalexan** [comment]
I see this locally due to a very unusual build output directory structure.  I am addressing it by adding
```
android {
  defaultConfig {
      // Used by Robolectric based tests; see TestRunner.
      buildConfigField 'String', 'BUILD_DIR', "\"${project.buildDir}\""
  }
}
```
and then using a custom test runner, based on https://github.com/robolectric/robolectric/issues/1648#issuecomment-113731011, that references said field.  This pollutes the `BuildConfig` class with a build-machine specific path, which sucks, but it's a small pain for a nice gain.

It's not clear to me that Gradle library `buildConfigField` are exposed in consuming libraries and applications, but if they are, we could make this happen automatically.  Has this been considered?  Are there additional concerns?

**Comment by eddnav** [comment]
@paulrs I'm running into this issue, if it isn't too much trouble, could you elaborate on this "Gradle-aware Make"?

**Comment by scottdarch** [comment]
As far as I can tell the bug has  two parts:

1. The Android gradle build system is not properly generating BuildConfig with `FLAVOR="androidTest"` as one would expect.
2. [RobolectricGradleTestRunner.java#57](https://github.com/robolectric/robolectric/blob/master/robolectric/src/main/java/org/robolectric/RobolectricGradleTestRunner.java#L57) is improperly adding `"full"` to the manifest path. 

If RobolectricGradleTestRunner simply omitted this constant and if Android was properly setting the FLAVOR to "androidTest" I believe this would work.

**Comment by scottdarch** [comment]
I'm able to work around this issue in a custom test runner by using the following logic:
```
private static FileFsFile findManifest(String flavor, String type) {
    final String[] buildIntermediates = new String[]{"build/intermediates", "manifests", flavor, type, "AndroidManifest.xml"};
    if(!FileFsFile.from(buildIntermediates[0], buildIntermediates[1]).exists()) {
        // no local manfests. Search in bundles.
        buildIntermediates[1] = "bundles";
    }
    if (null == flavor || flavor.length() == 0) {
        // No flavor. Look first in androidTest...
        buildIntermediates[2] = "androidTest";
        if (!FileFsFile.from(buildIntermediates[0], buildIntermediates[1], buildIntermediates[2]).exists()) {
            // ...then look in the legacy "full" folder...
            buildIntermediates[2] = "full";
            if (!FileFsFile.from(buildIntermediates[0], buildIntermediates[1], buildIntermediates[2]).exists()) {
                // ...and finally just set to the default flavor.
                buildIntermediates[2] = "";
            }
        }
    }
    return FileFsFile.from(buildIntermediates);
}
```

I'd submit a patch but I'm not able to get robolectric building on my machine (It can't find the maps shadows in maven for some reason).

**Comment by jongerrish** [comment]
We've revamped resources in Robolectric 4.0 to process the binary resource files + arsc table produced by aapt and the resource handling code is now much closer to that of the framework. This includes changes to parse the merged manifest using the Android platform code.

Mind giving this a try with 4.0 + binary resources by configuring your gradle.build as follows:-

```groovy
testImplementation "org.robolectric:robolectric:4.0"

android {
  enableUnitTestBinaryResources=true
  testOptions {
    unitTests {
      includeAndroidResources = true
    }
  }
}
```

We're doing a big bug scrub and trying to be aggressive about it so apologies if this was closed in error, in which case feel free to reopen.

If this is still an issue an example project with failing test would be most helpful.
