### ISSUE TITLE
WebSettings implementation restricts methods to wrong API level

### ISSUE THREAD

**Issue by 1zaman** [robolectric/robolectric#2097]
`RoboWebSettings.java.vm` incorrectly restricts method implementations to higher API levels. For example, the `setLoadsImagesAutomatically()` method was available since API level 1, but it is defined in the API 22 section.

**Comment by erd** [comment]
If you want to submit a PR, I'd be happy to review it.

**Comment by 1zaman** [comment]
I’ll try to work out a pull request over the weekend if I get the time.

**Comment by bdwain** [comment]
i submitted #2101 to address this

**Comment by bdwain** [comment]
@1zaman any idea what some of these methods are that are overriding methods that don't even exist on WebSettings? Like getUserAgent or setUseWebViewBackgroundForOverscrollBackground. I left them in the API level 22 section because i didn't want to delete them without knowing what they were for, but I don't see how they can be marked as @Override since the method does not exist in the parent class (this broke my original build when they weren't restricted to API level 22)

**Comment by 1zaman** [comment]
Looks like these methods were deprecated quite early on (Donut and Honeycomb respectively it looks like), and then finally hidden from the public API in Jelly Bean MR 1. It’s still present in the source code though, and it looks like all unimplemented methods were copied from the source and set to API 22 in commit bbc7bd63ccc57594a539ce382b080310fe940516.
