### ISSUE TITLE
ShadowSystemClock.setCurrentTimeMillis doesn't set the current time

### ISSUE THREAD

**Issue by charlesmunger** [robolectric/robolectric#2118]
```
ShadowSystemClock.setCurrentTime(1034100100, TimeUnit.NANOSECONDS);
assertThat(scheduler.getCurrentTime(TimeUnit.NANOSECONDS)).isEqualTo(1034100100);
```

This simple snippet of code doesn't actually work - setCurrentTime doesn't actually set the current time any more, as that's now the responsibility of the master scheduler. This was a breaking change, in cf1f6ba6b124c8deca19d04c3d792c9268991d19, with no announcement or even javadoc change. Can we revert?

**Comment by jongerrish** [comment]
I'm now feeling that it will be better to revert these breaking changes since we have this issue, plus the deadlock issue which could be harder to fix.

How about we do this:-

Revert some / all of these scheduler changes so we can get a stable version at head.

Replay those changes onto a new branch were Jeremy can iron out the kinks and we can periodically test these changes on our large corpus of tests at Google and merge them back into main as they become stable?

**Comment by kriegfrj** [comment]
@jongerrish, I'm happy in principle to keep these changes on a separate branch until you've had a chance to test them against your extensive corpus. As I recall, this was originally the plan. Perhaps we got a little bit too cavalier, or perhaps @erd felt sorry for you because you were so busy trying to keep up with it we decided to skip these changes. :smile:

In regard to this particular issue with cf1f6ba, though, I don't think there is a problem or anything that should stop us from including it and I think it was premature for us to revert it. This is based on a misunderstanding/misreading of how `SystemClock` works and a confusion of the different clocks it supports. I won't go into too much detail here, but as the documentation for [android.os.SystemClock](http://developer.android.com/reference/android/os/SystemClock.html) states, the system clock backs `SystemClock.uptimeMillis()` and `System.nanoTime()` and measures time relative to some fixed (but arbitrary & implementation-dependent) point in time (usually boot time). It is guaranteed to be monotonic, can't (I believe) be set programmatically in Android, and doesn't necessarily correspond directly to the real-world time on the clock on your wall (ie, wall clock time). The wall clock, on the other hand, backs `System.currentTimeMillis()`, is supposed to correspond to the real-world time on the clock on your wall, is not guaranteed to be monotonic (ie, it could go backwards sometimes). The system clock is the clock that should be used for most interval timing (eg, the scheduling code; in real Android `MessageQueue`/`Looper` is based on this clock). What that as background:

> setCurrentTime doesn't actually set the current time any more, as that's now the responsibility of
> the master scheduler. This was a breaking change, in cf1f6ba, with no announcement or even 
> javadoc change. Can we revert?

With greatest respect and due deference to the poster and whatever problems he was facing, the above statement is inaccurate and the snippet of code *should* fail:

Firstly, `setCurrentTime()` didn't actually *exist* prior to cf16ba. How, then, can it be claimed that this was a breaking change? (To be fair, the changes to `setCurrentTimeMillis()` on the other hand were "breaking", but this is a slightly different case and I'll get to that later.)

Secondly, `setCurrentTime()` *is* documented with Javadoc, which explains exactly what this method is supposed to do - which is to set the *wall clock* time.

Thirdly, `setCurrentTime()` does exactly what the documentation says that it does - it sets the *wall clock*. It does *not* set the system clock (the clock used by the master scheduler). That is why the code snippet in the OP didn't work - it *shouldn't* work.

Having said that, I think that the fact that @charlesmunger got confused is in itself an issue that perhaps points to a need for more extensive javadoc to emphasise the difference between the clocks (perhaps with a reference back to the Android doc) in order to minimise the chance of confusion. Perhaps also changing the method name to `setCurrentWallTime()` might help to make its functionality more clear - I chose the name `setCurrentTime()` to try and maintain consistency with `setCurrentTimeMillis()` (whose functionality it is intended to mimic).

With respect to `ShadowSystemClock.setCurrentTimeMillis()` - I acknowledge that my change to this method was a departure from the pre- cf16ba behaviour. Pre- cf16ba, the following code would have worked: 

````
// Suppose that we start with uptimeMillis() == 100
ShadowSystemClock.setCurrentTimeMillis(1034);
assertThat(scheduler.getCurrentTime()).isEqualTo(1034);
assertThat(SystemClock.uptimeMillis()).isEqualTo(1034);
````

However, I would argue that this implementation was irretrievably broken, and thus that my change was a necessary *fixing* change rather than a *breaking* change.

The fundamental problem is that `setCurrentTimeMillis()` (as defined by Android) is supposed to set the wall clock, and setting the wall clock is not supposed to affect the system clock (ie, shouldn't change `uptimeMillis()`). In order to properly emulate Android behaviour, it was necessary to break the tie between the system and wall clocks (or, more precisely, to make the tie adjustable rather than fixed at 0). In doing so, I could choose to preserve the invariant `fgScheduler.getCurrentTime() == uptimeMillis()` or the invariant `fgScheduler.getCurrentTime() == System.currentTimeMillis()`, but I obviously could not preserve both at the same time and so had to make a departure from historical behaviour. I decided that the scheduler time was a more natural match with the system clock and hence decided to preserve that invariant - which required me to break the invariant.

There were also some other problems with the `setCurrentTimeMillis()` implementation as it stood:
* It wouldn't let you rewind the wall clock. The Android documentation explicitly says that the wall clock can go backwards (assuming that the process calling it has permission to adjust it).
* It would set the clock by calling `Scheduler.advanceTo()`, which in turn would run all of the scheduled events in the meantime. Most of these events would have been scheduled with the assumption that they were scheduled against the system clock, and so to have them execute when the wall clock changes would be a surprise to most people (I think).

To be fair, I realise that these changes were significant enough that perhaps I could/should have raised & addressed them a separate issue rather than rolling them in with the change to the nanosecond timebase. However, I would argue that the combined javadoc of both `SystemClock` and `ShadowSystemClock` should have made it clear what the behaviour should be.

I also realise that by splitting the clocks there is now no facility to schedule events to happen at a particular time according to the wall clock. I have thought about adding a separate scheduler which is tied to the wall clock rather than the system clock, but that's a way down the track. Similarly for emulating the behaviour of the `elapsedRealtime()` clock and the affect of deep sleep.

Thoughts/comments appreciated.
