### ISSUE TITLE
ShadowDateUtilsTest failing since 2016

### ISSUE THREAD

**Issue by flyingtoaster0** [robolectric/robolectric#2194]
On KitKat and above, Android is formatting dates in the form "1/1" instead of "1/1/2016" for example, but only for the current year. For past years, the format is always "1/1/2015".
This appears to happen in DateIntervalFormat.toSkeleton() where the date format is constructed.

This means that when we're expecting "1/1" in the test, we're instead getting "1/1/2015" because we're using Jan 1st, 2015 as the date.

**Comment by jongerrish** [comment]
The date formatting code in Android has changed since JellyBean for
DateUtils:-

Jelly Bean - Uses a pure Android Java custom implementation -
https://github.com/android/platform_frameworks_base/blob/jb-mr1-release/core/java/android/text/format/DateUtils.java#L1110

KitKat - Uses libicu wrapper -
https://github.com/android/platform_frameworks_base/blob/kitkat-release/core/java/android/text/format/DateUtils.java#L826
https://github.com/robolectric/robolectric/blob/master/robolectric-shadows/shadows-core/src/main/resources/org/robolectric/shadows/ShadowDateIntervalFormat.java.vm

We use ICU4J to format the dates from Kit Kat and above.

Have you checked and confirmed what the correct behavior is on a Kit Kat +
device?

If Robolectric is inconsistent with a real device would you mind at least
creating an issue on the tracker, or even better, send a Pull Request to
fix it :-)

Jonathan
