### ISSUE TITLE
ShadowImageView could call through to real code more

### ISSUE THREAD

**Issue by xian** [robolectric/robolectric#2264]
`setImageDrawable()`, `setImageResource()`, and `setImageBitmap()` might as well call through to real code. Then we'll get image measurements and stuff.

**Comment by jongerrish** [comment]
I just checked our corpus of tests and it doesn't look like anyone is using the accessors on ShadowImageView that expose the internals of ImageView, I'd vote to just remove the shadow entirely in this case personally.

**Comment by xian** [comment]
> I'd vote to just remove the shadow entirely in this case personally.

Cool with me :-)

**Comment by xian** [comment]
@jongerrish bump

**Comment by jongerrish** [comment]
Thought you were gonna just remove the shadow entirely? If not let me know
and I'll merge as is.

**Comment by xian** [comment]
Oops, git is hard. ;-)

**Comment by xian** [comment]
@jongerrish bump :-)

**Comment by jongerrish** [comment]
I think this can be closed now?

I restored the class slightly as it turned out I missed a bunch of references in our test corpus

https://github.com/robolectric/robolectric/commit/6b80bc057c4870265f122c7c412c4e6d73b411e5

...this is a non-invasive shadow (just peeks rather than re-implements) and I marked the methods as deprecated to have a path to removing the shadow again.

Feel free to reopen if I missed anything.
