### ISSUE TITLE
Robolectric fails to load raw file resources due to invalid downcast.

### ISSUE THREAD

**Issue by jfhamlin** [robolectric/robolectric#2349]
`AssetFileDescriptor afd = getResources().openRawResourceFd(R.raw.file_name);` erroneously returns `null` after trying to cast a `BufferedInputStream` to a `FileInputStream`.

The leaf method, `FileFsFile#getInputStream()`, wraps a `FileInputStream` in a `BufferedInputStream`:

``` java
  @Override
  public InputStream getInputStream() throws IOException {
    return new BufferedInputStream(new FileInputStream(file));
  }
```

But `ShadowResources#openRawResourceFd()` expects a `FileInputStream`:

``` java
  @Implementation
  public AssetFileDescriptor openRawResourceFd(int id) throws Resources.NotFoundException {
    try {
      FileInputStream fis = (FileInputStream)openRawResource(id);
      return new AssetFileDescriptor(ParcelFileDescriptor.dup(fis.getFD()), 0, fis.getChannel().size());
    } catch (Exception e) {
      return null;
    }
  }
```

I assume we can do without the `BufferedInputStream`.

Here's the call stack:

```
getInputStream():78, FileFsFile {org.robolectric.res}
getRawValue():83, XResourceLoader {org.robolectric.res}
getRawValue():47, OverlayResourceLoader {org.robolectric.res}
getRawValue():51, RoutingResourceLoader {org.robolectric.res}
openRawResource():382, ShadowResources {org.robolectric.shadows}
openRawResourceFd():388, ShadowResources {org.robolectric.shadows}
invoke0():-1, NativeMethodAccessorImpl {sun.reflect}
invoke():62, NativeMethodAccessorImpl {sun.reflect}
invoke():43, DelegatingMethodAccessorImpl {sun.reflect}
invoke():497, Method {java.lang.reflect}
run():437, ShadowWrangler$ShadowMethodPlan {org.robolectric.internal.bytecode}
openRawResourceFd():-1, Resources {android.content.res}
```

**Comment by bjenning04** [comment]
My team just ran into this issue yesterday. I modified `getInputStream()` on `FileFsFile` to return just the `FileInputStream` and ran into a couple downstream issues.
* `ParcelFileDescriptor.dup(fis.getFD())` throws an NPE because `Os.dup(orig)` returns `null`. I fixed this issue by just using `orig`.
**ParcelFileDescriptor**
```
public ParcelFileDescriptor(FileDescriptor fd) {
    this(fd, null);
}

public ParcelFileDescriptor(FileDescriptor fd, FileDescriptor commChannel) {
    if (fd == null) {
        throw new NullPointerException("FileDescriptor must not be null");
    }
    mWrapped = null;
    mFd = fd;
    mCommFd = commChannel;
    mGuard.open("close");
}

public static ParcelFileDescriptor dup(FileDescriptor orig) throws IOException {
    try {
        final FileDescriptor fd = Os.dup(orig);
        return new ParcelFileDescriptor(fd);
    } catch (ErrnoException e) {
        throw e.rethrowAsIOException();
    }
}
```
* When my `MediaPlayer` attempts to open the `AssetFileDescriptor` returned from `openRawResourceFd()`, it throws an NPE because `getFileDescriptor()` is called on `AssetFileDescriptor`, which in turn calls `getFileDescriptor()` on the `ParcelFileDescriptor` passed to `AssetFileDescriptor` earlier, and `ShadowParcelFileDescriptor` overrides this method to return the `FileDescriptor` from a `RandomAccessFile` that is currently `null`. I fixed this by extending `ShadowParcelFileDescriptor` and using the real object to get the `FileDescriptor` if the `RandomAccessFile` is `null`.
**AssetFileDescriptor**
```
private final ParcelFileDescriptor mFd;

public FileDescriptor getFileDescriptor() {
    return mFd.getFileDescriptor();
}
```

**ShadowParcelFileDescriptor**
```
private RandomAccessFile file;

@Implementation
public FileDescriptor getFileDescriptor() {
    try {
        return file.getFD();
    } catch (IOException e) {
        throw new RuntimeException(e);
    }
}
```

This is all with Robolectric 3.0 so some of these issues may already be resolved, but thought I would be a good community member and note my findings.

**Comment by jongerrish** [comment]
We've revamped resources in Robolectric 4.0 to process the binary resource files + arsc table produced by aapt and the resource handling code is now much closer to that of the framework. This includes changes to parse the merged manifest using the Android platform code and an overhaul of our PackageManager support.

Mind giving this a try with 4.0 + binary resources by configuring your gradle.build as follows:-

```groovy
testImplementation "org.robolectric:robolectric:4.0"

android {
  enableUnitTestBinaryResources=true
  testOptions {
    unitTests {
      includeAndroidResources = true
    }
  }
}
```

We're doing a big bug scrub and trying to be aggressive about it so apologies if this was closed in error, in which case feel free to reopen.

If this is still an issue an example project with failing test would be most helpful.
