### ISSUE TITLE
Issues with android.support.design library 23.2.0

### ISSUE THREAD

**Issue by tehras** [robolectric/robolectric#2418]
Hi All,
Using Robolectric 3.0.

Not sure if anyone else has run into the same issues, but when upgrading to design library 23.2.0 my unit tests began failing.
I run them on sdk = 18, and it seems that the design library 23.2.0 started using some new way ??? of getting drawables, which totally bashes my unit tests. When i try running on sdk = 21, they run fine, except I get OutOfMemory issues after about 350 unit tests. I've tried fixing that issue as well, but no luck in either case. Has anyone else found a resolution for this?

On SDK 18 I tried extending the ShadowResources and ShadowDrawables where it was failing and putting some not so good fixes in there, but it seems every time i fix an issue, a new one comes along. 
I'll be working on this, and maybe trying to fix the sdk 21 issue instead today, so if i find anything i will comment, but I'm hoping someone else ran into this and had a good fix. 

Thanks

**Comment by jongerrish** [comment]
I'm actually looking at this issue now, although I'm on vacation and not
able to dedicate 100% effort to it.

What version of Robolectric are you using? One problem was that Robolectric
was shadowing a lot of code in Context/ContextWrapper which interfered with
the hacks app compat was using to make vectors work pre-api 21 (by using
custom ContextWrapper and Resources) I've fixed this at head by killing a
lot of the redundant shadowing code, preferring framework code instead.

I think there may also be a resource mismatch so the problem may not be
100% solved, but I'm still aware of the issue and it's my first priority.

I'd definitely encourage you to run robolectric against the latest api
possible and track down the memory leaks. You should ensure your tests are
not leaking any app state between tests, if it's a Robolectric issue, I.e.
leaking android resources between tests then please create an issue with
profiling data.
On Apr 18, 2016 9:54 AM, "Taras Koshkin" <notifications@github.com> wrote:

Hi All,
Not sure if anyone else has run into the same issues, but when upgrading to
design library 23.2.0 my unit tests began failing.
I run them on sdk = 18, and it seems that the design library 23.2.0 started
using some new way ??? of getting drawables, which totally bashes my unit
tests. When i try running on sdk = 21, they run fine, except I get
OutOfMemory issues after about 350 unit tests. I've tried fixing that issue
as well, but no luck in either case. Has anyone else found a resolution for
this?

On SDK 18 I tried extending the ShadowResources and ShadowDrawables where
it was failing and putting some not so good fixes in there, but it seems
every time i fix an issue, a new one comes along.
I'll be working on this, and maybe trying to fix the sdk 21 issue instead
today, so if i find anything i will comment, but I'm hoping someone else
ran into this and had a good fix.

Thanks

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub
<https://github.com/robolectric/robolectric/issues/2418>

**Comment by tehras** [comment]
I'm using Robolectric 3.0.

Is there a good way to profile to find memory leaks in unit tests?

**Comment by jongerrish** [comment]
Can you try using 3.1-SNAPSHOT and see if that fixes your problem?

We should be pushing a release now, it's really overdue.

You can use a Java profiler such as yourkit / jprofiler and check out the
heap allocation.

**Comment by tehras** [comment]
Trying with sdk=21 for 3.0 and JProfiler, interestingly it's not actually running out of space, it just gets super slow where 1 test takes about a minute? Have you seen that before? I'm going to continue to try.

**Comment by jongerrish** [comment]
No... I'd imagine that would happen if we're not freeing up memory. Does
memory grow constantly or is it being garbage collected regularly?

You can also profile to see where the test is spending most of its time
also. Probably there are optimizations we can and should do.

Will be interesting to see these results. Feel free to create an issue for
this and attach any profile data you can capture.

**Comment by jaredsburrows** [comment]
`OutOfMemory issues after about 350 unit tests`. Are you using Java 7?

This normally happens on CIs that did not bump their perm memory. If you JDK8, you will not have this problem.

**Comment by jongerrish** [comment]
If you switch to binary resources it is significantly faster and consumers less memory:-

We've revamped resources in Robolectric 4.0 to process the binary resource files + arsc table produced by aapt and the resource handling code is now much closer to that of the framework. This includes changes to parse the merged manifest using the Android platform code.

Mind giving this a try with 4.0 + binary resources by configuring your gradle.build as follows:-

```groovy
testImplementation "org.robolectric:robolectric:4.0"

android {
  enableUnitTestBinaryResources=true
  testOptions {
    unitTests {
      includeAndroidResources = true
    }
  }
}
```

We're doing a big bug scrub and trying to be aggressive about it so apologies if this was closed in error, in which case feel free to reopen.

If this is still an issue an example project with failing test would be most helpful.
