### ISSUE TITLE
Robolectric can't use non-static inner classes as shadows

### ISSUE THREAD

**Issue by Pr0methean** [robolectric/robolectric#2443]
### Description
When I try to use a non-static inner class of the test class as a shadow, I get a RuntimeException with "Could not instantiate shadow, missing public empty constructor." This message is misleading; and where the outer class is the test class, it shouldn't happen, because it should be clear what instance to invoke it on.
### Robolectric & Android Version
3_1_SNAPSHOT, Android API level 16

**Comment by jongerrish** [comment]
You could probably achieve this doing something like this:-

public static Object createInner(Object testObject, Class innerClass) {
  Constructor<?> ctor = innerClass.getDeclaredConstructor(testObject.getClass());
  return ctor.newInstance(testObject);
}

But since the shadows are instantiated deep within Robolectric, you'd need to plumb all of this in.

I've encountered this for creating Activity / Service inner instances in tests, but to be honest, I'm not sure of the value here, because this can all be achieved by static nested classes.

Generally speaking, I think the best use of shadowing is for Framework code that we don't control and ideally we want users to upstream any fixes or missing functionality so that the community can benefit.

What is your specific use case?

**Comment by jongerrish** [comment]
I'm going to close this as unfeasible since I haven't heard a reply. Feel free to submit a Pull Request.

**Comment by metallious** [comment]
This is a hack, what you could do is create another class (that is not `inner`) and make it inherit from your inner class and then use that one instead.
