### ISSUE TITLE
Provide a way to properly test configuration changes

### ISSUE THREAD

**Issue by jsotuyod** [robolectric/robolectric#2504]
### Description
Currently, the closest thing we get to configuration changes is calling `recreate`. However, `isChangingConfigurations` is not shadowed, and will always return false.

Having a method in `ActivityController` to take a shadow, set `isChangingConfigurations` to true, call `recreate` and reset `isChangingConfigurations` would probably be good enough for most scenarios.

Bonus points for detecting in the manifest if the activity is to handle configuration changes and avoid recreation, but at this point, even providing two separate methods and letting the developer choose would be a huge win for lifecycle testing.

### Robolectric & Android Version
Robolectric 3.0, al Android versions

**Comment by mag** [comment]
Could you provide a bit more detail? I'm curious about this, because my (rather dim) understanding of all this is that activity.recreate() does in fact mimic a configuration change, at least in some ways. 

Specifically, in respect to fragment lifecycle and the `setRetainInstance()` method.  In Robolectric, during `recreate()` when a fragment has called `setRetainInstance(true)`, you will get a second call to `onActivityCreated()` on the exact same `Fragment` object; yet if you have `setRetainInstance(false)`, the Android code will instantiate a brand new `Fragment`. This is realistic behavior (except that even when retaining the Fragment instance, `onCreate()` should have been called on recreation - this is an inconsistency between Robolectric and real Android, I'm pretty sure).

So what we might actually want is a way to mimic a "hard" activity recreation - the kind that happens when Android actually kills an Activity (or process I guess) and you come back to the app and the system recreates your Activities and Fragments. This is the type of recreation that happens when you use the "Don't Keep Activities" switch in the developer options setting screen. In this situation, `onRetainInstance()` doesn't do jack - you'll get new `Fragment` instances regardless. And in fact it's a brand new `Activity` instance as well. Robolectric doesn't let you test this case if you are also using `setRetainInstance(true)`, AFAICT. What we have done on my project is to just stop using `setRetainInstance(true)`, thus making both of these cases equivalent and forcing us to save helpful state during `onSaveInstanceState()`. This works for us but I can imagine some users wanting to differentiate these two different types of activity recreation.

**Comment by jsotuyod** [comment]
Thanks for your quick reply. Let me explain the concrete scenario.

I'm building an app using MVP, where Fragments and Actitivies take the role of pure views. The views tell the presenter when the view is attached / detached, to make sure no references are leaked / avoid ilegal access to detached views. However, not all "detach" means the presenter itself is to be stopped, since this "view unavailability" can be temporal due to a configuration change (ie: the phone is rotated and the view is recreated in landscape). This allows the presenter to decide if background taks (network calls, async tasks, etc.) are to be cancelled or not.

To achieve this, my base actvity does something such as:

```java
@Override
protected void onCreate(final Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    initPresenter();
    presenter.attachView(this);
}

@SuppressWarnings("unchecked")
private void initPresenter() {
    presenter = (MvpPresenter<V>) getLastCustomNonConfigurationInstance();

    if (presenter == null) {
        presenter = createPresenter();
    }
}

@Override
protected void onDestroy() {
    presenter.detachView(isChangingConfigurations()); // Tell the presenter if this is permanent or temporal
    super.onDestroy();
}

@Override
public final Object onRetainCustomNonConfigurationInstance() {
    if (isChangingConfigurations()) { // save the presenter instance if needed
        return presenter;
    } else {
        return null;
    }
}
```

I want to test therefore that `detachView` is called with the proper value on each scenario. However, `isChangingConfigurations()` will always return false (the method is not shadowed), meaning I can't test this scenario properly.

`recreate` is equivalent to a configuration change in terms of lifecycle (events triggered are the same, in the same order, on the expected instances), but does nothing as for the value being returned by `isChangingConfigurations()`.

I believe, adding a utility method to `ActivityController` to actually produce a configurationChange would be greatly useful. Of couse, just shadowing the method and making it return true during the following `recreate` would be assuming a config change for the activity is not handled by the activity itself (the manifest has no `android:configChanges` definition for the activity), but that of course is only needed for completeness, and not for my current scenario.

Please let me know if this is still not clear enough or I can be of any further assistance this!

**Comment by mag** [comment]
Ah, thanks for that explanation. Makes sense now.

So yeah, I think a method on `ActivityController` to simulate a configuration change would be really awesome! Feel free to take a shot at it :) 

I'm curious about whether your understanding of

**Comment by jsotuyod** [comment]
Ok, I'm currently working on this. I believe I can achieve it quite easily. I'll try to send a PR ASAP.
