### ISSUE TITLE
Problems asserting nextActivity with Robolectric 3.1

### ISSUE THREAD

**Issue by martijndebruijn** [robolectric/robolectric#2521]
### Description
I've upgraded to Robolectric 3.1 and all my asserts on nextStartedActivity() are failing. 

String url = "http://test.com";
final Intent expectedIntent = new Intent(Intent.ACTION_VIEW, Uri.parse(url));
assertThat(shadowOf(activity).getNextStartedActivity()).isEqualTo(expectedIntent);

Although the internal intent data (bundle, action, etc) is the same the equals fails. It looks like the assert  is done on the toString method.

java.lang.AssertionError: expected:
<'Intent { act=android.intent.action.VIEW dat=http://test.com } (Intent@6a77718e)'>
 but was:
<'Intent { act=android.intent.action.VIEW dat=http://test.com } (Intent@47c0583d)'>
### Robolectric & Android Version
Robolectric 3.1, Android

**Comment by StrangeLooper** [comment]
We are experiencing a very similar issue after upgrading from 3.0 to 3.1 on the same assertion.

The intent data matches as @martijndebruijn pointed out, but there appears to be an extra newline on the expected. Here is a screenshot from the IDE:

<img width="1334" alt="intentcomparisonissue" src="https://cloud.githubusercontent.com/assets/2363229/16199805/08d0845a-36d9-11e6-8326-e4b082c4cbb0.png">

**Comment by jongerrish** [comment]
This is due to the removal of code from ShadowIntent, specifically that .equals() was incorrectly used to shadow Intent.equals() which I think is just Object.equals(). Which is how your assertion happened to work before.

I recommend using an assertion library like assertj and the assertj-android square extension, where you can use the following to make your assertion in a cleaner and more readable way.

https://github.com/square/assertj-android/blob/master/assertj-android/src/main/java/org/assertj/android/api/content/IntentAssert.java

I'll update the migration doc.

**Comment by geoffreywiseman** [comment]
FWIW, this kind of assertion is still used in the "Writing your First Test" example -- should I file a separate issue to address this?
