### ISSUE TITLE
NPE Using AlarmManager in v3.1.2

### ISSUE THREAD

**Issue by ScottPierce** [robolectric/robolectric#2669]
### Description

Getting a NPE while using AlarmManager.

``` Java
AlarmManager alarmManager = (AlarmManager) RuntimeEnvironment.application.getSystemService(Context.ALARM_SERVICE);

// Later on a background thread I call the below statement. The call results in the below error.
alarmManager.setExactAndAllowWhileIdle(AlarmManager.RTC_WAKEUP, nextAlarmTimestamp, pendingIntent);
```

```
java.lang.NullPointerException
    at android.app.AlarmManager.setImpl(AlarmManager.java:464)
    at android.app.AlarmManager.setExactAndAllowWhileIdle(AlarmManager.java:668)
...
```
### Robolectric & Android Version

Roblectric version 3.1.2
Using android sdk 23 with robolectric, but using 24 to compile.

**Comment by anitawoodruff** [comment]
I get the same NPE when testing code that calls `alarmManager.setWindow()` - is it simply because these methods aren't implemented in Robolectric's [ShadowAlarmManager](https://github.com/robolectric/robolectric/blob/master/robolectric-shadows/shadows-core/src/main/java/org/robolectric/shadows/ShadowAlarmManager.java )?

I don't really know how Robolectric works but I note that if I change the code to call alarmManager.set() or setAndAllowWhileIdle() instead (which *are* implemented) it does not throw the NPE.

**Comment by jongerrish** [comment]
Yes, it is missing the shadow for this relatively new method that was added
in API 23

You can just add a the implementation similar to all the other set*()
methods:-

https://github.com/robolectric/robolectric/blob/master/robolectric-shadows/shadows-core/src/main/java/org/robolectric/shadows/ShadowAlarmManager.java

Want to send a PR with a test?

**Comment by anitawoodruff** [comment]
Sure, I'll give it a go!

**Comment by jongerrish** [comment]
You can check the project out from github, it builds with Gradle now,
instructions are at the bottom here, let me know if you get stuck...

https://github.com/robolectric/robolectric

**Comment by anitawoodruff** [comment]
I've checked it out and installed dependencies but not sure how to run the right tests, without running all of them.. I tried`./gradlew test --tests "*ShadowAlarmManagerTest*"` but it said 'No tests found'

(the instructions to run Robolectric's tests with maven at http://robolectric.org/contributing/ are out of date, right?)

**Comment by jongerrish** [comment]
Ya, they're out of date, I've created the following tracker entry to fix
this:- https://www.pivotaltracker.com/story/show/134374649

You should be able to just run ./gradlew test to run all tests, not sure
how to specify test filters, but if you find out let me know :-)

You can also just run a single test from within IntelliJ / Android Studio
directly.

**Comment by anitawoodruff** [comment]
I tried to import the project into Android Studio, but I'm having issues:

- After import I get the message "Error:The modules 'parent', 'buildSrc' point to same directory in the file system.
Each module has to have a unique path."

- All the `@RunWith(TestRunners.MultiApiWithDefaults.class)` annotations are not found, underlined in red. I think maybe because the `org.robolectric.annotations.Config` file cannot resolve `org.jetbrains.annotations.NotNull` - the import and usages are underlined and if I try to run tests it fails with "Error:(5, 33) java: package org.jetbrains.annotations does not exist"

For the record I found out how to run a single test class from command line - you have to specify the submodule too:

    ./gradlew -D:robolectric:test.single=ShadowAlarmManagerTest robolectric:test

But it would be very nice to be able to edit the code using Android Studio if I can get it configured correctly! Any help appreciated.

**Comment by jongerrish** [comment]
Are you importing the gradle project? robolectric/build.gradle - this works
for me

**Comment by anitawoodruff** [comment]
Yup, that's exactly what I'm doing (Android Studio > Import Project > select top level build.gradle ) . 

Not the end of the world though since I can run tests from command line just fine with that command. PR created!

**Comment by anitawoodruff** [comment]
@jongerrish is there any chance of a new release of Robotica happening soon with this fix in? It would be really great to get the [Habitica](https://github.com/HabitRPG/habitica-android) tests passing again! All the [recent pull requests](https://github.com/HabitRPG/habitica-android/pulls) have been in the red due to this bug :( Thanks!

**Comment by jongerrish** [comment]
Ya, a new release will be coming shortly. We'll land API 25 support and fix
a couple of remaining side effect issues with the resources refactoring so
end of this week beginning of next hopefully.

**Comment by seadowg** [comment]
@anitawoodruff @jongerrish I'm having exactly the same issue importing the project into Android Studio (`Error:The modules 'parent', 'buildSrc' point to same directory in the file system`). Did you ever solve this?
