### ISSUE TITLE
Nullpointer exception occurs when try to get UnicodeCharacter from KeyEvent

### ISSUE THREAD

**Issue by ahmadshahzad** [robolectric/robolectric#2779]
Nullpointer exception occurs when try to get UnicodeCharacter from KeyEvent.Java

````
java.lang.NullPointerException
	at org.robolectric.shadows.ShadowKeyCharacterMap.get(ShadowKeyCharacterMap.java:122)
	at android.view.KeyCharacterMap.get(KeyCharacterMap.java)
	at android.view.KeyEvent.getUnicodeChar(KeyEvent.java:2518)
````

````java
	@Test
	public void onKeyEvent_ActionDown() throws Exception {
		KeyEvent event = new KeyEvent(KeyEvent.ACTION_DOWN, -1);
		int metaState = event.getMetaState();
		event.getUnicodeChar(metaState);
	}
````
 above test will generate the exception.

Android version 22 and Robolectric 3.1.4

**Comment by lkorth** [comment]
This also occurs for any symbol (`!@#$%`, etc) used.

**Comment by kenrhe** [comment]
+1
Same error occurs when the below line is executed:
``mEditText.dispatchKeyEvent(new KeyEvent(KeyEvent.ACTION_DOWN, KeyEvent.KEYCODE_DEL))``

**Comment by nicusorflorin** [comment]
any progress on this? it's still occurs on 4.0 version

**Comment by utzcoz** [comment]
Hi @hoisie , maybe this problem is fixed by commit https://github.com/robolectric/robolectric/commit/738309a371f7f76531d547a20002b0caa51500e2, and the above mentioned tests can run without error with current source code. The tags of this commit show the robolectric can process above problems correctly from robolectric-4.2.

**Comment by hoisie** [comment]
Thanks!
