### ISSUE TITLE
"No tests were found" when running test class in IntelliJ

### ISSUE THREAD

**Issue by alixwar** [robolectric/robolectric#2815]
### Description
When running tests for a class in IntelliJ I get the error: 

> Process finished with exit code -2
> Empty test suite.

This used to work in Robolectric 3.1.4.

I have the following project structure (Multi-module):

```
+---module1
|   build.gradle
|   \---src
|       +---main
|       |   |   AndroidManifest.xml
|       |   |   
|       |   +---res
|       |   |   \---values
|       |   |           strings.xml
|       \---test
|           \---java
|               \---example
|                    |   FooTest.java
+---module2
etc
```

### Steps to Reproduce
Run FooTest:
```java
@Config(sdk = Build.VERSION_CODES.KITKAT, manifest = "./src/main/AndroidManifest.xml")
@RunWith(RobolectricTestRunner.class)
public class FooTest {
  @Test
  public void test() {
  }
}
```

### Robolectric & Android Version
Robolectric 3.2

Other relevant versions:
Android
- compileSdkVersion 25
- buildToolsVersion "25.0.2"
- minSdkVersion 19
- targetSdkVersion 22

Gradle
- com.android.tools.build:gradle:2.2.0

IntelliJ 2016.3

**Comment by xian** [comment]
Do you see any other error messages? The `@Config(emulateSdk)` is suspicious, `emulateSdk` was renamed to `sdk` around Robolectric 3.0.

**Comment by klinker41** [comment]
I'm seeing a similar error to this with version 32., except I think for different reasons.

Currently, I've configured my tests to run with multiple SDK versions:
```java
@RunWith(RobolectricTestRunner.class)
@Config(sdk = {16, 25}, constants = BuildConfig.class)
```

When I try and run an individual test, I get the following error logged:
```
java.lang.Exception: No tests found matching Method test_putIntoIntent(xyz.klinker.android.article.data.ArticleTest) from org.junit.internal.requests.ClassRequest@1ef7fe8e

	at org.junit.internal.requests.FilterRequest.getRunner(FilterRequest.java:40)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:98)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
```

It looks like when you add multiple SDKs to test against, Robolectric will rename the tests to also include the SDK version run with, for example `test_putIntoIntent[16]`. My guess is that this is where IntelliJ is failing, it doesn't know about that renaming so it's simply trying to run `test_putIntoIntent`.

On a somewhat related note, even when I have tests running against multiple SDK versions, each is named the same thing. This means that I have 2 tests that get logged in the results when I run all tests, but they are named the same thing (`test_putIntoIntent[16]` and `test_putIntoIntent[16]` instead of `test_putIntoIntent[16]` and `test_putIntoIntent[25]`). I did however confirm that it was using different SDK versions for each by using `System.out.println(Build.VERSION.SDK_INT)` and saw `16` and `25` logged in their respective tests. This is definitely a separate problem, so I'm happy to open another issue for it if you'd prefer @xian.

**Comment by alixwar** [comment]
> Do you see any other error messages? The @Config(emulateSdk = ...) is suspicious: emulateSdk was renamed to sdk around Robolectric 3.0.

I will update my example. No more information in the logs unfortunately.

**Comment by xian** [comment]
I believe this issue is now fixed, please verify and reopen if not. Thanks!

**Comment by alixwar** [comment]
I can still reproduce this in 3.2.2

**Comment by xian** [comment]
Any other details you can provide? Is this a focused method run? Does it work from the command line?

**Comment by alwa** [comment]
It works from commandline (has always worked). Both focused method and class run fails. Running ordinary unit tests without the Robolectric runner works.

**Comment by alixwar** [comment]
It now works (3.2.2). I had missed to update the dependencies in some modules (they were set to 3.2). This ticket is resolved.

**Comment by adebayoshogo** [comment]
Getting an error message No tests found in the class "" after running my tests
