### ISSUE TITLE
How can I tell the roboletric to find the manifest in the source

### ISSUE THREAD

**Issue by supernewbie1979** [robolectric/robolectric#2891]
by default it is looking the file at `build\intermediates\manifests\full\` and even I change it to 
`@Config(constants = BuildConfig.class, sdk = 16,manifest = "src/main/AndroidManifest.xml")`
and it starts looking it from `build\intermediates\manifests\full\devApp\debug\src\main\AndroidManifest.xml`

Is there anyway to do that? thanks.

**Comment by Th4n** [comment]
Are you sure you have proper working directory set in Android Studio JUnit run configuration?

**Comment by Vandalko** [comment]
huh, just faced the same issue - no matter if I run it from Gradle console or directly in AS.
I use Robolectric 3.2.2 on multiple projects and have this issue only on the one with flavors.

**Comment by Vandalko** [comment]
Spent some time digging in `GradleManifestFactory` due to misconfigured tests...

@supernewbie1979 the best way to achieve desired behavior is to extend `RobolectricTestRunner.getManifestFactory` and provide your own implementation which would grab manifest from sources.

Because current implementation allows you to pick manifest only from resources or build directory (and this makes sense since result manifest got to be merged including libraries code; and if you want to test some specific manifest - just put it into the test resources)

**Comment by IgorGanapolsky** [comment]
@Vandalko How to use **getManifestFactory**?

**Comment by jongerrish** [comment]
We've revamped resources in Robolectric 4.0 to process the binary resource files + arsc table produced by aapt and the resource handling code is now much closer to that of the framework. This includes changes to parse the merged manifest using the Android platform code.

Mind giving this a try with 4.0 + binary resources by configuring your gradle.build as follows:-

```groovy
testImplementation "org.robolectric:robolectric:4.0"

android {
  enableUnitTestBinaryResources=true
  testOptions {
    unitTests {
      includeAndroidResources = true
    }
  }
}
```

We're doing a big bug scrub and trying to be aggressive about it so apologies if this was closed in error, in which case feel free to reopen.

If this is still an issue an example project with failing test would be most helpful.
