### ISSUE TITLE
Robolectric version 3.3.2: unit tests fail when run on Jenkins

### ISSUE THREAD

**Issue by 1ud0v1c** [robolectric/robolectric#3132]
### Description

I am currently trying to develop my own framework, for tests purpose I tried to use the last version of Robolectric. When I run my tests under Android Studio, I have no issues but 
as soon as I use the command line (with gradlew) or run my unit tests on my jenkins server they fail. Here is the error message I get after running a gradlew test --debug: 

```
ActivityDialogTest > initializationError FAILED
    java.lang.NoSuchMethodError

FAILURE: Build failed with an exception.

...

java.lang.NoSuchMethodError: com.google.common.collect.Lists.reverse(Ljava/util/List;)Ljava/util/List;
	at org.robolectric.ConfigMerger.getConfig(ConfigMerger.java:42)
	at org.robolectric.RobolectricTestRunner.getConfig(RobolectricTestRunner.java:394)
	at org.robolectric.RobolectricTestRunner.getChildren(RobolectricTestRunner.java:214)
	at org.junit.runners.ParentRunner.getFilteredChildren(ParentRunner.java:426)
	at org.junit.runners.ParentRunner.getDescription(ParentRunner.java:351)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:359)
        ...
```

Here is my build.gradle dependencies:

```
dependencies {
    compile fileTree ( dir: 'libs', include: ['*.jar'] )
    compile "com.android.support:appcompat-v7:25.3.1"
    compile "com.google.code.gson:gson:2.8.0"
    testCompile 'org.hamcrest:hamcrest-integration:1.3'
    testCompile 'org.hamcrest:hamcrest-core:1.3'
    testCompile 'org.hamcrest:hamcrest-library:1.3'
    testCompile('junit:junit:4.12') {
        exclude module: 'hamcrest-core'
    }
    testCompile('com.squareup:fest-android:1.0.+@aar') {
        exclude group: 'com.android.support', module: 'support-v4'
    }
    testCompile('org.robolectric:robolectric:3.2.2')
}
```

And finally my ActivityDialogTest class :

```
@Config(sdk = 18)
@RunWith(RobolectricTestRunner.class)
public class ActivityDialogTest {
    private ActivityDialog activityDialog;

    @Before
    public void setUp() throws Exception {
        activityDialog = Robolectric.buildActivity(ActivityDialog.class).attach().get();
    }

    @Test
    public void myTest() {
    }
}
```

### Steps to Reproduce

Run with the command: 

`
gradlew test
`

Or run on a Jenkins server

### Robolectric & Android Version

compileSdkVersion 25
buildToolsVersion "25.0.3"
testCompile 'org.robolectric:robolectric:3.3.2'

**Comment by zawadz88** [comment]
I'm experiencing the same issue on Robolectric 3.3.2 and 3.4.2
This started happening after migrating to Android Gradle Plugin 3.0.0-beta4 and Gradle 4.1.

**Comment by jongerrish** [comment]
Looks like there is a conflicting version of Guava on your classpath, must be a very old version because Lists.reverse() has been in Guava since v7: https://google.github.io/guava/releases/22.0/api/docs/com/google/common/collect/Lists.html#reverse-java.util.List-

Run

./gradlew dependencies

to see a dependency graph

https://docs.gradle.org/current/userguide/userguide_single.html#sec:listing_dependencies

**Comment by zawadz88** [comment]
Thanks @jongerrish !
So in our case we had:
`implementation 'com.google.collections:google-collections:1.0'`
which was causing this problem.
After changing to 
`implementation 'com.google.guava:guava:20.0'`
the error went away :)
While Guava is a much larger library this isn't necessarily an issue for us since we use ProGuard anyway.

FYI `./gradlew dependencies` doesn't work as expected with the latest version of Gradle as dependencies are not resolved immediately and you cannot see the entire dependency tree :/

**Comment by jongerrish** [comment]
Looks like there is an Android specific version of Guava api 22+, so maybe we should switch to this?

https://github.com/google/guava/wiki/Release22

**Comment by jon-w1** [comment]
@zawadz88 we're having the same issue, but cannot find where the conflict is coming from. You mentioned that `./gradlew dependencies` doesn't work as expected -- is there another command that can help find the culprit?

**Comment by zawadz88** [comment]
Hi @jon-w1,
Maybe you could use a build-scan? https://scans.gradle.com/get-started
