### ISSUE TITLE
ShadowBitmap createBitmap overwrites original width/height

### ISSUE THREAD

**Issue by SalvatoreT** [robolectric/robolectric#3242]
### Description
ShadowBitmap's [createBitmap method](https://github.com/robolectric/robolectric/blob/793ee1db287b053127b6e60891c3dbfd1ce4bc54/shadows/framework/src/main/java/org/robolectric/shadows/ShadowBitmap.java#L305-L320) applies a matrix transformation to the bitmap but then saves the scaled width and height to both the `width`/`height` and `createdFromWidth`/`createdFromWidth` fields.
```java
    if (matrix != null) {
      shadowBitmap.appendDescription(" using matrix " + shadowOf(matrix).getDescription());

      // Adjust width and height by using the matrix.
      RectF mappedRect = new RectF();
      matrix.mapRect(mappedRect, new RectF(0, 0, width, height));
      width = Math.round(mappedRect.width());
      height = Math.round(mappedRect.height());
    }
    if (filter) {
      shadowBitmap.appendDescription(" with filter");
    }

    shadowBitmap.createdFromBitmap = src;
    shadowBitmap.createdFromX = x;
    shadowBitmap.createdFromY = y;
    shadowBitmap.createdFromWidth = width;   // we just changed the "created from" width
    shadowBitmap.createdFromHeight = height; // I don't think that is right (I could be wrong)
    shadowBitmap.createdFromMatrix = matrix;
    shadowBitmap.createdFromFilter = filter;
    shadowBitmap.width = width;   // this mutated width fine
    shadowBitmap.height = height; // it is supposed to change
```

### Steps to Reproduce
I ran into this while attempting to update Picasso to the latest and greatest Robolectric. https://github.com/square/picasso/pull/1637 

Here's [one of the broken tests](https://github.com/SalvatoreT/picasso/blob/f9ee6da36230a8633577c8e39b5239ef093b6ada/picasso/src/test/java/com/squareup/picasso/BitmapHunterTest.java#L805) in Picasso from BitmapHunterTest ([on my updated branch](https://github.com/SalvatoreT/picasso/tree/salvatoret/update-agp)).
```java
  @Test public void centerCropWithGravityHorizontalRight() {
    Bitmap source = Bitmap.createBitmap(20, 10, ARGB_8888);
    Request data = new Request.Builder(URI_1).resize(40, 40).centerCrop(Gravity.RIGHT).build();

    Bitmap result = transformResult(data, source, 0);

    ShadowBitmap shadowBitmap = shadowOf(result);
    assertThat(shadowBitmap.getCreatedFromBitmap()).isSameAs(source);
    assertThat(shadowBitmap.getCreatedFromX()).isEqualTo(10);
    assertThat(shadowBitmap.getCreatedFromY()).isEqualTo(0);
    assertThat(shadowBitmap.getCreatedFromWidth()).isEqualTo(10); // breaks here
    assertThat(shadowBitmap.getCreatedFromHeight()).isEqualTo(10);

    Matrix matrix = shadowBitmap.getCreatedFromMatrix();
    ShadowMatrix shadowMatrix = shadowOf(matrix);
    assertThat(shadowMatrix.getPreOperations()).containsOnly("scale 4.0 4.0");
  }
```

### Robolectric & Android Version
This bug was introduced in #2752 and shipped in robolectric-3.2-rc1.

cc @JakeWharton @cesar1000 @xian

**Comment by jongerrish** [comment]
Thanks for the report, would you be up for submitting a PR? We'll get it in
quick for the next release.

On Jul 14, 2017 3:49 PM, "Salvatore Testa" <notifications@github.com> wrote:

Description

ShadowBitmap's createBitmap method
<https://github.com/robolectric/robolectric/blob/793ee1db287b053127b6e60891c3dbfd1ce4bc54/shadows/framework/src/main/java/org/robolectric/shadows/ShadowBitmap.java#L305-L320>
applies a matrix transformation to the bitmap but then saves the scaled
width and height to both the width/height and createdFromWidth/createdFromWi
dth fields.

    if (matrix != null) {
      shadowBitmap.appendDescription(" using matrix " +
shadowOf(matrix).getDescription());

      // Adjust width and height by using the matrix.
      RectF mappedRect = new RectF();
      matrix.mapRect(mappedRect, new RectF(0, 0, width, height));
      width = Math.round(mappedRect.width());
      height = Math.round(mappedRect.height());
    }
    if (filter) {
      shadowBitmap.appendDescription(" with filter");
    }

    shadowBitmap.createdFromBitmap = src;
    shadowBitmap.createdFromX = x;
    shadowBitmap.createdFromY = y;
    shadowBitmap.createdFromWidth = width;   // we just changed the
"created from" width
    shadowBitmap.createdFromHeight = height; // I don't think that is
right (I could be wrong)
    shadowBitmap.createdFromMatrix = matrix;
    shadowBitmap.createdFromFilter = filter;
    shadowBitmap.width = width;   // this mutated width fine
    shadowBitmap.height = height; // it is supposed to change

Steps to Reproduce

I ran into this while attempting to update Picasso to the latest and
greatest Robolectric. square/picasso#1637
<https://github.com/square/picasso/pull/1637>

Here's one of the broken tests
<https://github.com/SalvatoreT/picasso/blob/f9ee6da36230a8633577c8e39b5239ef093b6ada/picasso/src/test/java/com/squareup/picasso/BitmapHunterTest.java#L805>
in Picasso from BitmapHunterTest (on my updated branch
<https://github.com/SalvatoreT/picasso/tree/salvatoret/update-agp>).

  @Test public void centerCropWithGravityHorizontalRight() {
    Bitmap source = Bitmap.createBitmap(20, 10, ARGB_8888);
    Request data = new Request.Builder(URI_1).resize(40,
40).centerCrop(Gravity.RIGHT).build();

    Bitmap result = transformResult(data, source, 0);

    ShadowBitmap shadowBitmap = shadowOf(result);
    assertThat(shadowBitmap.getCreatedFromBitmap()).isSameAs(source);
    assertThat(shadowBitmap.getCreatedFromX()).isEqualTo(10);
    assertThat(shadowBitmap.getCreatedFromY()).isEqualTo(0);
    assertThat(shadowBitmap.getCreatedFromWidth()).isEqualTo(10); // breaks here
    assertThat(shadowBitmap.getCreatedFromHeight()).isEqualTo(10);

    Matrix matrix = shadowBitmap.getCreatedFromMatrix();
    ShadowMatrix shadowMatrix = shadowOf(matrix);
    assertThat(shadowMatrix.getPreOperations()).containsOnly("scale 4.0 4.0");
  }

Robolectric & Android Version

This bug was introduced in #2752
<https://github.com/robolectric/robolectric/pull/2752> and shipped in
robolectric-3.2-rc1.

cc @JakeWharton <https://github.com/jakewharton> @cesar1000
<https://github.com/cesar1000> @xian <https://github.com/xian>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/robolectric/robolectric/issues/3242>, or mute the thread
