### ISSUE TITLE
RobolectricTestRunner.getBuildSystemApiProperties leaks file descriptors

### ISSUE THREAD

**Issue by amandeepg** [robolectric/robolectric#3252]
### Description
When Robolectric tests are run, each one opens up `/com/android/tools/test_config.properties` via `RobolectricTestRunner.getBuildSystemApiProperties`, but doesn't close it. This causes the file descriptor count to keep increasing, observed through `lsof`, eventually causing a `(Too many open files in system)` error.

### Robolectric & Android Version
3.3.2

**Comment by amandeepg** [comment]
Fixed in https://github.com/robolectric/robolectric/pull/3253

**Comment by jongerrish** [comment]
Thanks for the fix Amandeep. How is the integration working out for you
guys?

On Jul 19, 2017 12:05 PM, "Amandeep Grewal" <notifications@github.com>
wrote:

Closed #3252 <https://github.com/robolectric/robolectric/issues/3252>.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/robolectric/robolectric/issues/3252#event-1170843281>,
or mute the thread
