### ISSUE TITLE
Library tests can't find manifest or assets with upgrade to Android Plugin 3.0.0

### ISSUE THREAD

**Issue by ScottPierce** [robolectric/robolectric#3380]
### Description
I recently upgraded my app to use Android Plugin 3.0.0-beta5 and all of my library tests that use assets are failing. I had to work around it by specifying the manifest and asset directory explicitly.

```
@Config(
    sdk = intArrayOf(25),
    manifest = "build/intermediates/manifests/aapt/internal/debug/AndroidManifest.xml",
    assetDir = "../../../../../../src/main/assets"
)
```

Either Robolectric takes issue with upgrading to Android Plugin 3.0.0, or it takes issue with the fact that I had to create flavors in the library (which would make sense as the manifest directory is changes based on that)

### Robolectric & Android Version
Android Plugin 3.0.0-beta5
Android SDK 25
Robolectric 3.4.2

**Comment by jrodbx** [comment]
Looks related to this: https://issuetracker.google.com/issues/38039816#comment11

**Comment by jrodbx** [comment]
Filed separately as https://issuetracker.google.com/issues/65550419 per @jongerrish's request

**Comment by emartynov** [comment]
Just bumped into the same issue! Any workaround?

**Comment by jongerrish** [comment]
@emartynov @jrodbx I just chatted with the AGP team, and tests in library projects should be working with the following caveats:-

1) AndroidManifest.xml provided is not the merged manifest (i.e: won't contain entries specified in dependent libraries).
2) assets folder will not include the merged assets, only the assets for the current library which is being tracked in the issue John created above:  https://issuetracker.google.com/issues/65550419 

The best thing you can do is make your voice heard on the bug above, I know work has been done specifically to fix it but we just need to keep pushing to get it in the 3.0 final release, otherwise it will get bumped to 3.1 :-/

**Comment by emartynov** [comment]
Actually, I have failing tests not for the library but for the app project. And I'm going to comment on the Google bug tracker in hope to make it 3.0 release reachable.

**Comment by jongerrish** [comment]
@emartynov merged resources, assets and manifests should be working for the app.

* What version of Robolectric are you using?
* What version of AS + AGP are you using?
* Have you removed @Config(constants = BuildConfig.class) from your tests?

Can you provide the actual error?

**Comment by emartynov** [comment]
Answers:

- We are on Robolectric 3.4.2
- I can not run tests nor from AS 3.0 Beta 6, nor from command line AGP 3.0 Beta 6
- I've removed `constants` from tests

Error from command line run:
```
java.lang.SecurityException: class "android.databinding.Observable"'s signer information does not match signer information of other classes in the same package
	at java.lang.ClassLoader.checkCerts(ClassLoader.java:898)
```

Error from AS:
```
android.content.res.Resources$NotFoundException: Unable to find resource ID #0x0 in packages [android, com.myapp.package]
```

**Comment by jongerrish** [comment]
@emartynov - I don't think this is a related issue. I've tried to reproduce this by setting up a small databinding project and its working fine. Could you provide a test project so I can debug this? Feel free to make a change to https://github.com/robolectric/deckard - this is what I was using to try and repro.

Other than that, if you could include a full stack trace that would help. The fact that you are seeing "com.myapp.package" in the exception tells me that we are finding your resources.

**Comment by emartynov** [comment]
Sure, I'm going to play a bit with Deckard if I can reproduce it.

We use Kotlin, Databinding and Mockito that might affect build or code manipulation. So hope to finish it before the weekend.

Also, hate the fact that run from Studio produces different output form running from command line. That is several years mystery for me - didn't we switch to gradle to 100% reproducible things?

**Comment by jrodbx** [comment]
@jongerrish thanks!  added a comment: https://issuetracker.google.com/issues/65550419#comment13

**Comment by ankushg** [comment]
@jongerrish I'm running into a similar issue to @emartynov 

Robolectric isn't able to find my font in an **app project**, and the font isn't from a separate library/module. Unlike @emartynov, I'm getting an actual resource ID instead of `0x0`.

```
android.content.res.Resources$NotFoundException: Resource ID #0x7f040001
	at android.content.res.Resources.getValue(Resources.java:1233)
	at android.support.v4.content.res.ResourcesCompat.loadFont(ResourcesCompat.java:335)
	at android.support.v4.content.res.ResourcesCompat.getFont(ResourcesCompat.java:205)
```

The given Resource ID does map to a `font` resource in my debug configuration's `R.java`, and the corresponding font file is also present in `build/intermediates/res/merged/debug/font`.

I'm using Robolectric 3.5.1, AGP 3.0.1, and both AS 3.1 canary, and AS 3.0 stable. I've removed `constants` from tests. I've also tried it both with/without [making the Unit Test Sources task depend on Merging Assets](https://github.com/robolectric/robolectric/issues/2647#issuecomment-312652710).

Is this a known issue? Any ideas for how to try to work around it?

**Comment by jongerrish** [comment]
We've revamped resources in Robolectric 4.0 to process the binary resource files + arsc table produced by aapt and the resource handling code is now much closer to that of the framework. This includes changes to parse the merged manifest using the Android platform code.

Mind giving this a try with 4.0 + binary resources by configuring your gradle.build as follows:-

```groovy
testImplementation "org.robolectric:robolectric:4.0"

android {
  enableUnitTestBinaryResources=true
  testOptions {
    unitTests {
      includeAndroidResources = true
    }
  }
}
```

We're doing a big bug scrub and trying to be aggressive about it so apologies if this was closed in error, in which case feel free to reopen.

If this is still an issue an example project with failing test would be most helpful.
