### ISSUE TITLE
Provide a way to properly test configuration changes

### ISSUE THREAD

**Issue by dmitrikudrenko** [robolectric/robolectric#3661]
Main description is in #2504 but I would like to use it for FragmentController & SupportFragmentController.

**Comment by MGaetan89** [comment]
Hey @dmitrikudrenko,
`FragmentController` has been deprecated in favor of [`FragmentScenario`](https://developer.android.com/reference/androidx/fragment/app/testing/FragmentScenario), and `SupportFragmentController` no longer exists.
I'm closing this issue since you can probably achieve what you want with `ActivityController` and `FragmentScenario`. Otherwise, don't hesitate to open a new issue with the relevant details.
