### ISSUE TITLE
AGP compresses all assets for unit test .apk regardless of aaptOptions.noCompress

### ISSUE THREAD

**Issue by xian** [robolectric/robolectric#4091]
`java.io.FileNotFoundException: This file can not be opened as a file descriptor; it is probably compressed`

AGP compresses all assets for unit test `.apk` regardless of `aaptOptions.noCompress`.

Re-enable `AssetManagerTest.openFd_shouldProvideFileDescriptorForAsset` (disabled for #4077) and specify `aaptOptions.noCompress "txt"` or something.

**Comment by xian** [comment]
Not that I know of. We need to open a bug against Android Gradle Plugin's AAPT behavior for unit tests.

**Comment by vlafourcade** [comment]
Same issue here. Any update on that?

**Comment by utzcoz** [comment]
This issue is fixed by https://github.com/robolectric/robolectric/pull/6649, and https://github.com/robolectric/robolectric/issues/5442 has more details related this problem. Anyone has this problem, you can wait the next `Robolectric` release after 4.6.1, and bump AGP to `7.1.0-alpha08` or later versions to support `noCompress` of `aaptOptions` for unit test. I will closed it, and anyone can feel free to reopen it if there is any problem. cc @hoisie.
