### ISSUE TITLE
Common table expression throws SQLiteException

### ISSUE THREAD

**Issue by mattswitch** [robolectric/robolectric#4505]
### Description
Unable to create CTE queries on databases.

### Steps to Reproduce
Run any query as a common table expression, for example
```sql 
WITH one AS ( SELECT 1 ) SELECT * FROM one
```

The query passes running Espresso (and also running in a live application). But when running on Robolectric I get this exception:

`Caused by: com.almworks.sqlite4java.SQLiteException: [1] DB[1] prepare() WITH one AS ( SELECT 1 ) SELECT * FROM one [near "WITH": syntax error]`

### Robolectric & Android Version
Robolectric: v4.1
Android: 21-28

### Link to a public git repo demonstrating the problem:

https://github.com/mattswitch/SQLiteCTE-Robolectric

**Comment by leofirespotter** [comment]
Can confirm that this is a real issue, any ideas on how to fix?

**Comment by georgi-neykov-hub** [comment]
The issue is caused by the version of [SQLite4Java|https://bitbucket.org/almworks/sqlite4java/overview] being used, for Robolectric 4.2 it is still [`0.282`|https://mvnrepository.com/artifact/com.almworks.sqlite4java/sqlite4java/0.282], and in Maven Central there's a [newer version|https://mvnrepository.com/artifact/com.almworks.sqlite4java/sqlite4java/1.0.392] which is based on SQLite 3.8.7 which supports CTEs.

**Comment by georgi-neykov-hub** [comment]
I can make a PR with the change, but is there any specific reason to keep the old version of the library?

**Comment by ReginFell** [comment]
I've tried to force "com.almworks.sqlite4java:sqlite4java:1.0.392" and no luck, it doesn't seem that the issue was resolved

**Comment by georgi-neykov-hub** [comment]
I have submitted #5213 with the updated libraries, hope it helps and gets approved.

**Comment by jurgensr** [comment]
It still a problem in 'org.robolectric:robolectric:4.3.1'

**Comment by jurgensr** [comment]
Looks solved in org.robolectric:robolectric:4.5-alpha-1

**Comment by hoisie** [comment]
Since it's been fixed in #5216, I'll close this issue.
