### ISSUE TITLE
Unresolved reference: style

### ISSUE THREAD

**Issue by mradzinski** [robolectric/robolectric#4722]
### Description
Attempting to run tests on Android Studio 3.3.2 which were working fine on version 3.3.1 fail with `Unresolved reference: style` during build time. 

I'm pretty sure this isn't Robolectric's fault and it's most likely related to an Android Gradle Build Tools issue, but thought of mentioning it here. I've been able to reproduce this in around 5 different setups... well done Google, well done.

### Steps to Reproduce
Create an Activity which extends `AppCompatActivity`:
```
class TestActivity : AppCompatActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setTheme(R.style.Theme_AppCompat_NoActionBar) // <-- Obviously build fails here
    }
}
```

Now attempt to run any tests (it doesn't matter how, it'll fail during build time anyway). That's enough to make the build fail with the mentioned error. It's worth noting that UT binary resources are enabled and `testOptions.unitTests.includeAndroidResources = true` added to the build.gradle file.

### Robolectric & Android Version
Robolectric 4.2, AS 3.3.2

### Link to a public git repo demonstrating the problem:
Can't provide any atm, it's an internal project for the company I work for. I'll try setting up a project to share though.

**Comment by jongerrish** [comment]
Thanks for the report @mradzinski - you're right, this looks like an Android Gradle Build tools issue. For unit tests, even if you are not using Robolectric, the Android Gradle plugin should be generating the R.class for your project.

I'm making the assumption that you've got an androidImplementation on "androidx.appcompat:appcompat" and you're importing the R class from your module (that Theme_AppCompat_NoActionBar) should be merged into.

Just to give you the big picture, the R.class should always be generated so even if you're just using mockable jar your symbols will resolve, but specifying 

testOptions.unitTests.includeAndroidResources = true

will also generate the matching resources.ap_ file so that Robolectric can look up the resources from the matching R class.

I'm going to close this issue, but if it persists would you mind creating an issue on the Android build tools tracker.

Sorry for your pain.... for what its worth we're working on adding some sample projects using Android Build tools to we can have a demonstrable project with all the integrations working.
