### ISSUE TITLE
Document workaround for undeclared test activities

### ISSUE THREAD

**Issue by xian** [robolectric/robolectric#4727]
Until #4726 is fixed and generally available, Gradle users will need to employ a workaround in order to declare test activities in a manifest that's visible to Robolectric.

- [ ] Validate that workaround
- [ ] Add integration test
- [ ] Document the workaround on http://robolectric.org
- [ ] Add to 4.2 release notes

**Comment by realdadfish** [comment]
From #4725 
> Are you saying that even with a core-test module (containing testing infrastructure such as AndroidManifest.xml and com.my.TestActivity itself) and depending on that with
>
> testImplementation(project(":core-test"))
>
> from the module, your manifest entries in the core-testing are not merged either?

I didn't know the inner workings Robolectric applied before 4.2 to make test-only Activities visible for `ActivityScenario`, but I was (and am) aware that for instrumentation tests the `TestActivity` and `AndroidManifest.xml` has to reside in the application itself to be available for testing, which is why JetPacks `fragment-testing` artifact is documented to have to be added to the `debug` build type, like so:

    debugImplementation "androidx.fragment:fragment-testing:..."

(https://developer.android.com/training/basics/fragments/testing)

And since I thought that the ultimative goal is to write a test once and execute it everywhere, I applied my `core-test` module also to the `debugImplementation` configuration of my `feature` module that I wanted to test.

I very much welcome that Robolectric has the plan to not force me (like Android) to have test Activities in the target package / context, because this means possible side effects (through additional test dependencies being suddenly available in the production configuration, classloading issues, etc.) could pop up during regular debug development that the developer is not aware of, and I would really like Android instrumentation tests also dropping this requirement, but I just don't see that happen.

**Comment by xian** [comment]
Agreed, it sucks to force test code to live in prod.

Workaround documented here: #4736
Gradle fix tracked here: #4726.

4.2.1 will have a better exception message with a link to the workaround. Closing this issue.
