### ISSUE TITLE
Time zone with colon will not be parsed in the proper manner from 4.3

### ISSUE THREAD

**Issue by lupsyn** [robolectric/robolectric#5220]
### Description
This format "2019-08-15T11:41:00+02:00", will be not compatible with robolectric 4.3.
I should remove the colon in the time zone in order to fix and parse it properly with this : "yyyy-MM-dd'T'HH:mm:ssZ". 

It's same issue we have it https://github.com/robolectric/robolectric/issues/1030 .

In order to fix it, we have to shadow the deserialiser we use to parse the date, and remove the ':' from the date string.

**Comment by MGaetan89** [comment]
Hey @lupsyn,
This issue comes from the different JDK implementations between Android and your local JDK. There is nothing that Robolectric can do about it
We've added a [new documentation](https://robolectric.org/best-practices/#android-libcore-and-openjdk-have-different-implementations) for this to provide some tips. Please have a look, and don't hesitate to reopen this issue, or create a new one, if needed.
