### ISSUE TITLE
New version of Robolectric library

### ISSUE THREAD

**Issue by egorikftp** [robolectric/robolectric#5702]
### Description
Hello, do you have some roadmap with releasing new versions? I see that a huge amount of fixes already merged in master. 

The previous release was more than half a year ago.

**Comment by kingargyle** [comment]
Going to tag @brettchabot in this.   Is there any road map or time frame for at least an Alpha or Beta release of 4.4.   As has been stated above there are numerous performance fixes that we could benefit from sooner rather than later.  Prior versions had a better release schedule or at least a communicated release schedule.    I know that my projects tests could greatly benefit from the performance fixes that 4.4 regardless of any other features.

**Comment by neworld** [comment]
#5550 alone is a most welcome upgrade.

**Comment by hoisie** [comment]
Sounds good, I'll work on an alpha release of 4.4.

**Comment by hoisie** [comment]
4.4-alpha-1 is now released to Maven Central, you *should* be able to use it once it gets published to all the mirrors. https://repo1.maven.org/maven2/org/robolectric/robolectric/4.4-alpha-1/

**Comment by kingargyle** [comment]
@hoisie can we get this releases uploaded to GitHub as well, and any change log that goes with it?

**Comment by hoisie** [comment]
Just added the release to the Github page:

https://github.com/robolectric/robolectric/releases/tag/robolectric-4.4-alpha-1

I started on the changelog, but because the sheer size of this release (~430 distinct non-merge commits), the changelog may take a bit of time. I'll leave this issue open until that's done.

**Comment by ZacSweers** [comment]
@hoisie fyi that robolectric-annotations (and possibly others) are missing from the release artifacts on maven central

**Comment by ZacSweers** [comment]
Also what are the maven packages on github referencing 5.0? https://github.com/robolectric/robolectric/packages/150391

**Comment by hoisie** [comment]
@ZacSweers I did an end-to-end test of 4.4-alpha-1 before releasing it and it seemed to work. Are you referring to https://mvnrepository.com/artifact/org.robolectric/annotations/4.4-alpha-1? I believe it was renamed from `robolectric-annotations` to `annotations` at some point in the past. If you are seeing a compile error, let me know and I can take a closer look.

R.E 5.0 - I believe @xian is experimenting with some new concepts in the 5.0 branch, but I do not have all the details.

**Comment by hoisie** [comment]
Added release notes here:

https://github.com/robolectric/robolectric/releases/tag/robolectric-4.4-alpha-1

I'll start a 4.4-alpha-2 release as well.

**Comment by hoisie** [comment]
Out of curiosity has anyone tried out 4.4-alpha-1 or 4.4-alpha-2? Any issues so far?

**Comment by ZacSweers** [comment]
We updated to it today and it's working fine. Don't mock File and be prepared to do a little idle() calling for the new Looper

**Comment by hoisie** [comment]
OK great -- I'll do a beta release early next week

**Comment by hoisie** [comment]
4.4 is now released, closing this.
