### ISSUE TITLE
Enable ignored test for classloading issue

### ISSUE THREAD

**Issue by realdadfish** [robolectric/robolectric#5878]
https://github.com/robolectric/robolectric/blob/27f73bf04107a944ad42add183ec282cfa982428/integration_tests/mockito-experimental/src/test/java/org/robolectric/integrationtests/mockito/experimental/MockitoMockJavaFrameworkTest.java#L22

Mockito 3.5.6 was recently released, so you might want to enable this test to ensure no classloading issues. 

Thanks a lot for the fix! This issue was driving me nuts today after I upgraded to Mockito 3.5.x and in Robolectric tests my mocks weren't instantiated properly during test instance creation, leading to fake instances of `MockMethodDispatcher` being around.

**Comment by hoisie** [comment]
The weird thing is that if that `@Ignore` is removed and Mockito updated to 3.5.5, another tests starts failing due to MockitoRule:

https://github.com/robolectric/robolectric/blob/master/integration_tests/mockito-experimental/src/test/java/org/robolectric/integrationtests/mockito/experimental/MockitoMockFinalsTest.java#L20

I believe this may be an issue with MockitoRule, but I haven't tracked it down yet. It works fine if MockitoAnnotations.init(this) is used.

**Comment by realdadfish** [comment]
IIRC `MockitoAnnotations.initMocks(instance)` is deprecated in favor of `MockitoAnnotations.openMocks(instance)` (and an accompanying close call). Personally I removed all my instances of `initMocks` and replaced them with inline calls to `mock()` (from `mockito-kotlin`).

**Comment by hoisie** [comment]
Weirdly I got those tests passing using Mockito 3.4.6 and Robolectric 4.4. Something between 3.4.6 and 3.5.0 seems to break mocking Android objects in Robolectric tests. I'll try filing a bug and bisecting if I have time.
