### ISSUE TITLE
SystemClock.elapsedRealtime always return 100 in  robolectric.

### ISSUE THREAD

**Issue by 1312818364** [robolectric/robolectric#5937]
I used robolectric version is 4.3.1, I found when I call SystemClock.elapsedRealtime whenever, it always return 100, is different with mobile device.I want to konw  how to make it behavior like real mobile device?

**Comment by hoisie** [comment]
Although this is bizarre, this, this is actually working as intended. Robolectric does not have a free-running clock for uptime, and the starting value for the uptime clock is 100. Why does it have the value 100? I don't know, you may have to check the git history.

The reason it doesn't have a free-running clock is intentional to make testing Handlers/Loopers/MessageQueues more hermetic. For instance, if you have application code that does `handler.post(task, 1 hour)`, you don't want the test to wait one your to run the task. So you can use ShadowLooper.idle() to run any pending tasks.

You can also use https://github.com/robolectric/robolectric/blob/master/shadows/framework/src/main/java/org/robolectric/shadows/ShadowSystemClock.java#L58 to set the time returned by SystemClock.elapsedRealtime.

If you want that mechanism to work like a real device, you may have to use an emulator.
