### ISSUE TITLE
Support shadow for androidx.localbroadcastmanager

### ISSUE THREAD

**Issue by utzcoz** [robolectric/robolectric#5974]
Current `ShadowLocalBroadcastManager` is under library `support-v4`, but there are many projects use `ShadowLocalBroadcastManager` under library `androidx.localbroadcastmanager`. Whether there is roadmap to support `androidx.localbroadcastmanager`? Thanks.

**Comment by utzcoz** [comment]
There is a workaround to test `LocalBroadcastManager`, that registers receiver for broadcasts with the same `LocalBroadcastManager` instance.

**Comment by hoisie** [comment]
Although not explicitly stated anywhere at the moment, we have a strong preference for not shadowing androidx classes, as they are largely wrappers for framework classes. If androidx classes have trouble working, we would prefer to shadow the associated android framework classes to make them work. I believe in the past a lot of support.v4 classes were shadowed in order to  fix issues with loopers/handlers, as the support library tends to use these extensively. I haven't looked too closely at support.v4 ShadowLocalBroadcastManager, but would it be possible to use the real androidx LocalBroadcastManager?

**Comment by utzcoz** [comment]
My workaround solution is to use androidx `LocalBroadcastManager` to register custom receiver to receive sent broadcast for test. At least, we can test it without shadows now that doesn't break the official rules, so I close this issue. @hoisie Thanks your response.
