### ISSUE TITLE
Deprecate supportv4 Shadows in Robolectric 4.6

### ISSUE THREAD

**Issue by alsutton** [robolectric/robolectric#6185]
Idea suggested in https://github.com/robolectric/robolectric/pull/6174#issuecomment-766188189. Creating an issue to track and centralise discussion.

**Comment by hoisie** [comment]
I think this would be fine to do. I don't think that there was any iteration these shadows, so folks can still depend on supportv4 shadows 4.5 if they need. We just have to make sure all public supportv4 shadow API is deprecated.

**Comment by alsutton** [comment]
Updating the bug title to reflect the decision to deprecate rather than remove.

**Comment by hoisie** [comment]
Also, specifically about SupportFragmentController: in general I am supportive if deferring to official Android testing APIs (FragmentScenario in this case). However, some of the official testing APIs are designed to work across all execution environments (e.g. emulators/real devices). Because of this, they can often be underpowered compared to the Robolectric equivalent, which has far fewer limitations. So before deprecating/removing SupportFragmentController, I just want to be sure there isn't some major testing use case that Robolectric supports that is not possible in FragmentScenario. I am not sure if there is, but it's something to keep in mind.

**Comment by alsutton** [comment]
Sounds prudent to me. I've updated the diff to deprecate everything except SupportFragmentController. My thinking is that if we get the deprecations into the codebase early folk will flag up any use cases which we're currently unaware of.

**Comment by utzcoz** [comment]
It is fixed by https://github.com/robolectric/robolectric/pull/6174.
