### ISSUE TITLE
Emoji/unicode are not handled

### ISSUE THREAD

**Issue by menny** [robolectric/robolectric#6433]
### Steps to Reproduce
Clone https://github.com/menny/RoboWithEmoji and run tests: `./gradlew :app:testDebugUnitTest`
Create an XML resource with unicode characters:
```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<Root
    label1="no emoji"
    label2="&#128512;"
    label3="😀" >
</Root>
```
Try and read the value from the  attributes:
```
val xml = resources.getXml(R.xml.doc_with_emoji)

while (xml.next() != XmlPullParser.END_DOCUMENT) {
    if (xml.eventType == XmlPullParser.START_TAG) {
        if ("Root" == xml.name) {
            val attrs = Xml.asAttributeSet(xml)
            val label1 = attrs.getAttributeValue(null, "label1")
            val label2 = attrs.getAttributeValue(null, "label2")
            val label3 = attrs.getAttributeValue(null, "label3")
        }
    }
}
```

while `label1` will be read correctly (`no emoji`), `label2` and `label3` will not, and will have the value `\uFFFD\uFFFD`.

### Robolectric & Android Version
Robolectric 4.5.1, AGP 4.2.0, latest SDK

### Link to a public git repo demonstrating the problem:
https://github.com/menny/RoboWithEmoji

**Comment by menny** [comment]
Of course, this works well on a device or emulator.

**Comment by menny** [comment]
I've created a few tests to show this: https://github.com/menny/RoboWithEmoji/blob/main/app/src/test/java/com/example/robowithemoji/ExampleUnitTest.kt

**Comment by hoisie** [comment]
Thank you for the detailed repro instructions.

**Comment by utzcoz** [comment]
After some days digging, I found the root cause is that the emoji/unicode is compressed with modified-utf8, but [ResourceString#decodeString](https://github.com/robolectric/robolectric/blob/7697d1217c5eb0dee454004efe60ba219f398255/resources/src/main/java/org/robolectric/res/android/ResourceString.java#L79) doesn't consider it, and uses normal `new String` directly. If I change to use `DataInputStream` to decode it based on [StackOverflow's problem Java 8 UTF-8 encoding issue (java bug?)](https://stackoverflow.com/questions/25404373/java-8-utf-8-encoding-issue-java-bug), it works fine, and above mentioned tests can pass correctly. Hi @hoisie I will send it with new PR for reviewing.

**Comment by menny** [comment]
thanks!
