### ISSUE TITLE
Can roboelectric be used to test a Non-UI system app? <Non-bug related query>

### ISSUE THREAD

**Issue by nikitph** [robolectric/robolectric#6480]
### Description
Can roboelectric be used to test a Non-UI system app? we are in a unique situation where we are using android to develop a system app which starts automatically on a dashcam. It doesnt have a UI but is using a broadcast receiver to spawn off a bunch of threads which need to be tested. How can we utilize RE for this?

### Robolectric & Android Version
android 8.1

**Comment by hoisie** [comment]
Sure, I don't see why not. You can think of Robolectric as a generic mechanism for setting up the environment that allows app and test code to call into the Android platform on the JVM. So because presumably your system app will invoke Android framework code, it should be runnable under Robolectric. 

The only complication is if you are targeting a custom Android platform that has a different API than AOSP.

**Comment by utzcoz** [comment]
Actually, the AOSP uses makefile to wrap Robolectric for system app, and you can leverage it to setup your environment. For example, the official settings app uses it to test itself. I can ensure it exists and worms fine on Android 8.1, but the limit is the Robolectric version, because it is more difficult to upgrade Robolectric version with makefile.

And it also works for non-UI system app, what I can comfirm. I have used it to test custom added system service, and it works fine. But for custom added system services, what we should do extra is to shadow custom system service, and add it to Robolectric framework such as what Robolectric does for AMS or other existing official system services.

**Comment by nikitph** [comment]
@hoisie @utzcoz  Thank you for your responses. It gives me great confidence to know that such a thing is possible. I am not deeply familiar with android internals but i will look at it based on what you have told me here. Would you guys happen to know of any code samples which will help me get started with what you have suggested?

**Comment by utzcoz** [comment]
https://android.googlesource.com/platform/packages/apps/Settings/+/refs/tags/android-8.1.0_r72/tests/robotests/ it is official settings example to use Robolectric to test system app with makefile build system based on 8.1 branch.

**Comment by nikitph** [comment]
@utzcoz this is great help thank you

**Comment by nikitph** [comment]
@utzcoz in the grander scheme of things, what does this makefile do? does it tell the roboelectric build to cache certain files? can I also include .so files in it?

**Comment by utzcoz** [comment]
> @utzcoz in the grander scheme of things, what does this makefile do? does it tell the roboelectric build to cache certain files? can I also include .so files in it? edit: should i read this https://developer.android.com/ndk/guides/android_mk

I think make files in this directory https://android.googlesource.com/platform/prebuilts/misc/+/refs/tags/android-8.1.0_r72/common/robolectric/ are better. The AOSP team creates makefile rules for Robolectric specifically based AOSP's common build rules. Especially https://android.googlesource.com/platform/prebuilts/misc/+/refs/tags/android-8.1.0_r72/common/robolectric/robotest-internal.mk and https://android.googlesource.com/platform/prebuilts/misc/+/refs/tags/android-8.1.0_r72/common/robolectric/run_robotests.mk. Actually, the robotests' `Android.mk` invokes [`run_robotests.mk`](https://android.googlesource.com/platform/packages/apps/Settings/+/refs/tags/android-8.1.0_r72/tests/robotests/Android.mk#43) directly to run robo tests. The AOSP didn't modify it largely until Android 10. I don't analyze and use it from Android 11, so I don't know the real changes from Android 11.

**Comment by utzcoz** [comment]
Hi @hoisie , is there any change to open discussion for Robolectric? The GitHub opens this function for all open source projects, and it can accept non-bug issues/problems/questions. I think discussion is better for normal question discussion with better quote and reply layout than issue. If yes, maybe we can transfer this problem to discussion for open discussing.

**Comment by nikitph** [comment]
my code has a library which depends on certain native .so files. How can i inculcate these in the cmake process?

**Comment by hoisie** [comment]
@nikitph Unfortunately I don't believe anyone here has much context in how Robolectric is build and included in the Android platform sources. I know that some Android teams (e.g. Settings, Backup&Restore) have been using Robolectric, but generally its use is discouraged in the Android Platform in favor of instrumentation and CTS tests. The version of Robolectric in the Android platform was forked a long time ago and is highly customized.

**Comment by utzcoz** [comment]
The Android platform team wrote some new makefile rules to support run Robolectric for system apps. And I think it will make upgrading of Robolectric difficult, because it doesn't support test binary with makefile rule now, but Robolectric 4.x that uses `AndroidX` test suite needs. I have used added rules and append our custom new rules to write test suite for internal Android system apps, and I can't upgrade added Robolectric version quickly. Also some basic makefile rules will change when we upgraded to Android big version, such as from Android 8 to Android 10, that causes the problem to port our Robolectric test suites rules. But I think current makefile rules support to add native so files to your Robolectric test runner target with so related `LOCAL_*` field. But you need load it with your classloader as @hoisie said, so you need to know the final position of your so files. Or you can customize current added makefile rules by Android team, and add custom `LOCAL_*` field to copy so files to your wanted position with shell commands, that is possible.

The instrumentation and CTS tests are more stable and upgradable. And if you can run your instrumentation tests with CI/Jenkins job every commit or everyday, instrumentation tests or CTS tests are better, and you can leverage [`atest`](https://source.android.com/compatibility/tests/development/atest) to run those tests more convenient. But the reason that we spend many time on Robolectric to add custom rules is that we can run those unit tests on commit build checking with other rules checking, such as code style. It's difficult for us to run instrumentation tests for every commit build, because our customized Android can't run on official emulator correctly and it is not stable with real devices. If you want to use Robolectric for your system app and benefit commit build convenient, I think you should `gradle` your system app, in another word, you should convert your system app from makefile build system to `gradle` build system. After that, you can use Robolectric likes a normal Android app, and your native so problem will be the same problem as https://github.com/robolectric/robolectric/issues/6123#issuecomment-854719201.

**Comment by utzcoz** [comment]
One updating for Robolectric on AOSP is that they upgraded Robolectric to 4.3.1 on master branch.

**Comment by utzcoz** [comment]
> As [bazel blog said](https://blog.bazel.build/2020/11/12/aosp_migrating_to_bazel.html), AOSP will migrate its build system to bazel, and I think it can bring Robolectric support to AOSP system app without any tricks. There are many [bazel rules at build/bazel master branch](https://android.googlesource.com/platform/build/bazel/+/refs/heads/master). I don't know whether Android 12 can support Robolectric with bazel for AOSP, we can check it after Android 12 source code release.

Hi @nikitph , before bazel integration, you can check https://cs.android.com/android/platform/superproject/+/master:packages/services/Mms/tests/robotests/Android.bp?q=android_robolectric_test as an example for integrating `Robolectric` with `Soong` for higher AOSP version for system apps.

I think it maybe current and some future AOSP plan for `Robolectric` integration for system apps, in my opinion. You can feel free to reopen it if you have any question.
