### ISSUE TITLE
Import errors running tests after migration version from 4.3.1 to 4.5.1.

### ISSUE THREAD

**Issue by pedrofsn** [robolectric/robolectric#6678]
### Description
I'm getting several errors about losing references/imports JUST when I run tests. 
I'm just upgrading robolectric library from version 4.3.1 to 4.5.1.
Any ideas?

```
Unresolved reference: Matchers
Unresolved reference: allOf
Unresolved reference: `is`
Unresolved reference: instanceOf
Unresolved reference: containsString
Unresolved reference: equalTo
```

**Comment by 200503** [comment]
https://www.bilibili.com

**Comment by 200503** [comment]
https://www.bilibili.com

**Comment by hoisie** [comment]
This sounds like this hamcrest issue:
https://github.com/robolectric/robolectric/issues/4355

You likely have two versions of hamcrest in the classpath.

Are you using org.mockito:mockito-all? This will bundle hamcrest in the uber jar.

The solution to this problem is to figure out where the extra hamcrest is coming from and exclude it.

Closing this because it is not a Robolectric issue.
