### ISSUE TITLE
Migrate Robolectric.setupActivity to ActivityScenario for Robolectric's tests if possible

### ISSUE THREAD

**Issue by utzcoz** [robolectric/robolectric#6877]
### Description

<del>There are tests of Robolectric use `Robolectric.setupActivity`, deprecated by Robolectric. Maybe we need to migrate those tests to use `ActivityScenario` if possible(except tests to test `Robolectric.setupActivity`). The example in README.md should also be updated with `ActivityScenario`.</del>

Migrate `Robolectric.setupActivity` to `ActivityScenario` for README.md and ctesque.

### Steps to Reproduce

Grep `setupActivity` at Robolectric source code.

### Robolectric & Android Version

Latest master branch.

### Link to a public git repo demonstrating the problem:

None.

**Comment by hoisie** [comment]
Just FYI, there are a few use cases of ActivityController that are not possible in ActivityScenario.

The main one is that in ActivityScenario, the Activity has to be registered in a manifest. This means that there's a lot more boilerplate to set up simple test-only activities. In Robolectric's test this happens a lot. I personally would not be a fan of all of this extra boilerplate.

Also, ActivityScenario uses ActivityController under the hood, so I think there is still value in ensuring that ActivityController has good test coverage.

**Comment by utzcoz** [comment]
> The main one is that in ActivityScenario, the Activity has to be registered in a manifest. 

Is it related AGP's manifest merging problem? I have saw some issues about it at Robolectric and issue-tracker.

There are very little things can do after excluding those use cases. Maybe only README.md left.

**Comment by hoisie** [comment]
I think the goal of ActivityScenario is that it can work in any execution environment, either Robolectric or emulator/device.

So if you try to run this in an emulator:

```java

import android.app.Activity;

  @Test
  public void launchActivity() throws Exception {
    ActivityScenario<Activity> activityScenario = ActivityScenario.launch(Activity.class);
  }
```

I believe it will fail because with an error that the Activity has not been declared in any manifest.

So ActivityScenario also enforces this constraint in a Robolectric environment as well, to ensure that tests written using AndroidX Test ActivityScenario does not work only in Robolectric.

However, for Robolectric tests, it is very convenient to do something like:

`Activity activity = Robolectric.setupActivity(Activity.class).get()`

I suppose what I'm trying to say is that it's not urgent to switch Robolectric's own tests (especially shadow tests) to use ActivityScenario, as it is highly unlikely that Robolectric's own tests will run in an emulator environment (except the ctesque tests).

I think it makes more sense to encourage Robolectric tests for apps to use ActivityScenario, as it is much more likely they will be testing Activities already declared in manifests.

**Comment by utzcoz** [comment]
> I suppose what I'm trying to say is that it's not urgent to switch Robolectric's own tests (especially shadow tests) to use ActivityScenario, as it is highly unlikely that Robolectric's own tests will run in an emulator environment (except the ctesque tests).

Agreed. The tests I want to migrate initial are tests under ctesque.

> I think it makes more sense to encourage Robolectric tests for apps to use ActivityScenario, as it is much more likely they will be testing Activities already declared in manifests.

I am writing slides about Robolectric. But README.md also uses `Robolectric.setupActivity` instead of `ActivityScenario` with `AndroidJUnit4` runner. I think I should use `ActivityScenario` as an example for Robolectric to encourage other new Robolectric users. If they encounter any problem about `ActivityScenario` on Robolectric, they can switch back to `setupActivity` as callback.

Many users may check Robolectric's tests to see how to use Robolectric to test something, at least I use this method, because there is no any official codelab or example repository(or I don't know) for Robolectric usage. It's better if we can migrate some tests under ctesque to use `ActivityScenario` ***if possible***.

**Comment by hoisie** [comment]
👍 for using ActivityScenario in the README + ctesque

**Comment by utzcoz** [comment]
> +1 for using ActivityScenario in the README + ctesque

Updated issue content. I will leave it for potential new contributors have interested in this problem some weeks. It is simple, and friendly for new contributor.

**Comment by utzcoz** [comment]
After long time consideration, IMO we don't need this issue as starter issue, because ctesque doesn't contain `setupActivity` anymore. And there is a PR to switch to use `ActivityController` in README.md. So I will close this issue.
