### ISSUE TITLE
Does `ActivityController#close()` need to be called to prevent leaks?

### ISSUE THREAD

**Issue by seadowg** [robolectric/robolectric#7041]
A [commit from a few months ago](https://github.com/robolectric/robolectric/commit/feaded1a56ba818ecc1f580f862f4f40c95b3627) adds a `close()` method to `ActivityController`. My assumption based on the docs/commit message here is that without calling this (or using `try-with-resource`), the underlying `Activity` object (and potentially other resources) will be leaked and not be reclaimed by GC while tests are running. Is that the case? If so, I think it makes sense to update docs so that this is clearer.

**Comment by utzcoz** [comment]
It's better to call `close()` after test. There are some related issues: https://github.com/robolectric/robolectric/issues/6998, https://github.com/robolectric/robolectric/issues/6262. Other folks have reported memory leak for other items when not closed after test.

**Comment by seadowg** [comment]
@utzcoz makes sense I'm happy to create a PR for [robolectric.github.io](https://github.com/robolectric/robolectric.github.io) if that's still considered the best place for docs. 

Out of interest is the need for `close()` a "recent" (since AndroidX Test compatibility was introduced) change or is it something existing that just hadn't been discovered as a problem?

**Comment by utzcoz** [comment]
> @utzcoz makes sense I'm happy to create a PR for [robolectric.github.io](https://github.com/robolectric/robolectric.github.io) if that's still considered the best place for docs.

Thanks. I think it's better to point out this practice for users. What about writing a post about it? Adding this practice at tutorial page is also fine. @hoisie what do you think about it?

> Out of interest, is the need for close() a "recent" (since AndroidX Test compatibility was introduced) change or is it something existing that just hadn't been discovered as a problem?

Sorry, I don't have enough context about it. `*Scenario` from androidx.test are related to your said compatibility problem. Looks like `ActivityController` is created by Robolectric itself. Maybe @hoisie could provide more thoughts about it.

**Comment by seadowg** [comment]
> In between tests is a different story. If you set up an Activity in each test, and forget to close them, it will usually be okay, and the Activity will eventually get GC'd, as Robolectric resets Android state in between each test. However, if an Activity has special logic that registers itself with third party libraries that have singletons (I think Kotlin flow is one example), it will not be eligible for GC.

@hoisie Seems like that makes sense! I guess there the "leak" is really caused by something in the Activity that needs clean up through the lifecycle (like a listener on a singleton for example) - Robolectric itself isn't holding onto any references it shouldn't be. Is that the case for `AcitivityScenario` as well?

**Comment by utzcoz** [comment]
Another thing found about `FragmentScenario`: there doesn't exist `FragmentScenarioRule` likes `ActivityScenarioRule` to close `FragmentScenario` after test.

**Comment by seadowg** [comment]
Thanks for the clarifications! So does everyone agree that adding `close()` to the docs at https://robolectric.org is the best way to resolve this issue/discussion? To be honest, it looks like http://robolectric.org/writing-a-test/ could do with an update anyway. I've already filed an issue to update the Android docs around `ActivityScenario` (https://issuetracker.google.com/issues/213412583).

**Comment by utzcoz** [comment]
@seadowg could you help to update example in `README.md` of this repo too? Migrating to use `ActivityScenario` instead of `Robolectric.setupActivity` with proper `close()` invocation.

**Comment by seadowg** [comment]
> could you help to update example in README.md of this repo too? Migrating to use ActivityScenario instead of Robolectric.setupActivity with proper close() invocation.

As far as I understand, `ActivityScenario` (and the rules) don't work "out of the box" with Robolectric - you also need to add the AndroidX Test dependencies. Maybe another update that's needed is to make it very clear in the `README` and in the docs that developers should depend on AndroidX Test instead and only use Robolectric if they really need to? That's my assumption of the direction this is all going in and would mean that Robolectric docs could just link to AndroidX Test ones (for the basic examples) rather than maintaining a duplicated set. I'm happy to look at making those changes (I can just assign myself to this issue) but it would be good to double-check that that lines up with the way that Google sees these tools moving in.

**Comment by seadowg** [comment]
> maybe @hoisie can help to provide more background about it

That would be great. As I said, my assumption is that the long term goal is for Robolectric to go more and more "under the covers" and have developers interact with AndroidX Test as much as possible. Other than the deprecations on `Robolectric` I don't think this intention is really stated anywhere, and the testing team weren't explicitly aiming for that last time I spoke to them at the last Dev Summit (which was 3 years ago though). 

I don't want to get too off-topic - my goal here was to make sure there was clarity around the use of `close()` but it'd be nice to make sure we're not documenting code that no one should really be using (other than the AndroidX Test library) and leading people down the wrong path.

**Comment by utzcoz** [comment]
I remember one occasion that uses `ActivityController` directly: old AOSP's system apps use Robolectric bound into AOSP build system to write local tests, and developers should use `ActivityController` for Activity related tests because this Robolectric is old(4.x was added about two years ago https://android.googlesource.com/platform/prebuilts/misc/+/08160cfa80b16a8602dc62c376818afb7b766353). For example, there are some legacy AOSP's tests with `ActivityController`: https://cs.android.com/android/platform/superproject/+/master:packages/apps/Launcher3/robolectric_tests/src/com/android/launcher3/widget/picker/search/WidgetsSearchBarControllerTest.java?q=ActivityController&ss=android&start=11.

**Comment by seadowg** [comment]
@hoisie do my assumptions all sound correct?

**Comment by hoisie** [comment]
cc @brettchabot 

Just to be clear is this conversation now about updating the home page `http://robolectric.org/` and `http://robolectric.org/writing-a-test/` to clarify the use of AndroidX Test?

> As far as I understand, ActivityScenario (and the rules) don't work "out of the box" with Robolectric - you also need to add the AndroidX Test dependencies.

Yeah, ActivityScenario is a separate library, it is not part of Robolectric itself. AndroidX Test is a compatibility layer that can work in both emulator and Robolectric environments. I like to think of Robolectric at the same layer as the Android framework, with some additional useful testing APIs.

> Developers should depend on AndroidX Test, and only use Robolectric if they really need to? 

Developers should use AndroidX Test if there is a desire to write tests that work across execution environments. If developers prefer to target Robolectric-only, it is not necessary to use AndroidX Test APIs. For example, if they are writing a telephony/WiFi/Bluetooth app and need those shadow APIs for testing, some of those tests will be Robolectric-only.

> That's my assumption of the direction this is all going in and would mean that Robolectric docs could just link to AndroidX Test ones (for the basic examples) rather than maintaining a duplicated set. I'm happy to look at making those changes (I can just assign myself to this issue) but it would be good to double-check that that lines up with the way that Google sees these tools moving in.

At this point I would probably be hesitant to delete Robolectric docs and just link to AndroidX Test ones. I would definitely be okay with having more links to http://robolectric.org/androidx_test/ and mentioning cross-platform testing with AndroidX Test.

> Testing team weren't explicitly aiming for that last time I spoke to them at the last Dev Summit (which was 3 years ago though).

The iteration on AndroidX Test has stalled a bit, mainly due to the team churn, and there are also some technical limiting factors. It has historically not been a top priority in Android platform to introduce rich/extensible public testing APIs, and there are limitations in Robolectric itself, such as the lack of realistic rendering, and a discrete scheduler, that also poses additional limitations on the possible APIs available in AndroidX Test. This results in a situation where AndroidX Test APIs have a lot of constraints. I am hoping we can offer clearer guidance around this in the future and explore some other areas in which the AndroidX Test APis can grow.

**Comment by seadowg** [comment]
> At this point I would probably be hesitant to delete Robolectric docs and just link to AndroidX Test ones.
> The iteration on AndroidX Test has stalled a bit
> I am hoping we can offer clearer guidance around this in the future and explore some other areas in which the AndroidX Test APis can grow.

Thanks for this @hoisie. It's really useful to get clarification on all of this, even if it's that there is still uncertainty around the direction. Given this I think it's better to update the docs on `http://robolectric.org/` with references to using `close` with `ActivityController` rather than replacing examples with `ActivityScenario`. Only slightly related, but I also think it would be good to remove the `@Deprecated` from `Robolectric.setupActivity`. I think it's great to point to AndroidX Test in its Java Doc, but for me personally (and I imagine others), that deprecation has been a source of confusion in whether docs updates should use `ActivityScenario` or `AcitivtyController` (through `Robolectric.setupActivity`). I can create a PR for that as well and we can discuss further there if it seems controversial. 

> Developers should use AndroidX Test if there is a desire to write tests that work across execution environments. If developers prefer to target Robolectric-only, it is not necessary to use AndroidX Test APIs, but it never hurts to use them wherever possible. For example, if they are writing a telephony/WiFi/Bluetooth app and need those shadow APIs for testing, some of those tests will be Robolectric-only.

👍. This is exactly where I see it at the moment. 10 years ago Robolectric was pretty much essential, but now I'd only want to see explicit Robolectric API usage when playing around with the "nitty gritty" parts of the Android SDK.

**Comment by utzcoz** [comment]
@seadowg Looks like [AndroidX Test  adds a lint to check unclosed `ActivityScenario`](https://github.com/android/android-test/pull/1411).

**Comment by seadowg** [comment]
> @seadowg Looks like https://github.com/android/android-test/pull/1411.

That'll definitely when it's released!
