### ISSUE TITLE
Calling GLSurfaceView does not stop the created gl thread

### ISSUE THREAD

**Issue by hoisie** [robolectric/robolectric#7194]
When GLSurfaceView is used, the gl thread created in GLSurfaceView does not get terminated after the test finished.

ShadowGLSurfaceView probably needs a @Resetter method that kills an existing threads? Another option is to terminate the thread in callOnDetachFromWindow, or to try to mimic the Android behavior of terminating the thread.

**Comment by Abdulrahman1890** [comment]
Inform me with more details plz

**Comment by utzcoz** [comment]
> Inform me with more details plz
> 

It's not recommended to trying multiple starter issues at once. If you have interested into one issue, please try to finish that one firstly, instead of trying multiple issues the same time. We don't have enough starter issues now, and they should be left for newbies. This behavior will affect other folks to leave interesting comment because they maybe think this issue is assigned to one folk commented before.

**Comment by Abdulrahman1890** [comment]
Oh, So sorry I wasn't know that.. I just want to contribute and solve an issue to be able to contribute in the main project with GSOC and send my proposal before the deadline

**Comment by arsalanahmad4** [comment]
@hoisie Can you please elaborate a little more on the issue?

**Comment by MGaetan89** [comment]
Closing, as this should be fixed by #9406.
