### ISSUE TITLE
Mockito.spy and View.addOnLayoutChangeListener is broken in Robolectric 4.9

### ISSUE THREAD

**Issue by nborodikhin** [robolectric/robolectric#7707]
### Description

A spied view does not register layout change listeners.

The  regression is introduced by https://github.com/robolectric/robolectric/commit/424ca08dd5b63ecb4dbd2be80f5ffdbd81861091:
```
Add support to ShadowView for inspecting OnLayoutChangeListeners
```

### Steps to Reproduce

A sample unit test:
```java
    @Test
    public void test() {
        Context context = Robolectric.buildActivity(Activity.class).create().get();

        View view = new FrameLayout(context);
        view = Mockito.spy(view); // 1

        AtomicBoolean invoked = new AtomicBoolean(false);

        view.addOnLayoutChangeListener((v, p1, p2, p3, p4, p5, p6, p7, p8) ->
                invoked.set(true)
        );

        // view = Mockito.spy(view); // 2

        view.layout(2, 3, 5, 9);

        assertTrue(invoked.get());
    }
```

Listener registration is broken on a spied object - if spying is done after listener registration (line marked `2`, instead of `1`) then test passes.

### Robolectric & Android Version

Robolectric 4.9
Mockito 4.1.0, 4.8.0

**Comment by hoisie** [comment]
Unfortunately this is working as intended, and is related to https://github.com/mockito/mockito/issues/2552

Robolectric shadows cache the instances they are shadowing. This bypasses the instance that Mockito spies create. When a mockito spy is created, the original object is not modified. This means that if you call the original object, the spy will not be invoked. And Robolectric caches this original object.

In general I would recommend testing behavior instead of interaction. So instead of checking that `onLayout` was called, run assertions on what the result of `onLayout` does.

**Comment by nborodikhin** [comment]
I see, thanks for the context.

> In general I would recommend testing behavior instead of interaction. So instead of checking that onLayout was called, run assertions on what the result of onLayout does.

Completely agree to this!
