### ISSUE TITLE
Memory leak in CppAssetManager2 / Themes ?

### ISSUE THREAD

**Issue by barney2k7** [robolectric/robolectric#8405]
### Description
Even though there have been many bug reports and fixes around memory leaks in CppAssetManager2 / Themes, we're still facing leaking memory as of robolectric 4.10.3 / android 13:

![Screenshot 2023-08-11 100102](https://github.com/robolectric/robolectric/assets/2900849/fd4c2d5b-bb0a-499e-9675-c0570d7cd5a7)
![Screenshot 2023-08-11 100130](https://github.com/robolectric/robolectric/assets/2900849/37d73d40-2fe5-4db4-8183-9c35bb9003d6)

### Steps to Reproduce
It seems to be possible to reproduce the issue using ActivityCompatStressTest that was added in #6063:
- create a new 'empty activity' project in Android Studio Giraffe
- put ActivityCompatStressTest into the test folder
- increase the iterations in ActivityCompatStressTest to 50000, add `System.out.println(i);` to the loop
- update build.gradle: 
```
android {
  ...
  testOptions {
    unitTests {
      includeAndroidResources = true
      all {
        systemProperty 'robolectric.enabledSdks', '33'
        minHeapSize = "128m"
        maxHeapSize = "512m"
      }
    }
  }
}
dependencies {
	implementation 'androidx.appcompat:appcompat:1.6.1'
	testImplementation 'junit:junit:4.13.2'
	testImplementation 'org.robolectric:robolectric:4.10.3'
	testImplementation 'androidx.test.ext:junit:1.1.5'
       ...
```
- run ActivityCompatStressTest with e.g. visualvm attached
- observe: the test crashes with 'java.lang.OutOfMemoryError: Java heap space' after around 21000 iterations (9 minutes)
![image](https://github.com/robolectric/robolectric/assets/2900849/a2a3a72d-2ace-4dcb-8881-9b0e93acb786)

### Robolectric & Android Version
Robolectric 4.10.3
Android 13 (api 33)

**Comment by ajeihala** [comment]
I've noticed the same issue with memory a couple of years ago. Later it was fixed partially by cleaning up resources after an activity is destroyed (it became important every activity gets destroyed in each test). But I measured it still leaked memory every time I instantiated a custom View. I did a little investigation and also came to a conclusion that it was because of the theme/resources and if I remember correctly was related to static members in Cpp Asset Manager. No easy fix found but would be nice to get it repaired eventually.

**Comment by barney2k7** [comment]
Many other tickets were eventually closed or abandoned due to lack of steps to reproduce.
This issue here however is quite easy to reproduce, so I hope somebody with more insight into robolectric's resource handling can take another look.

**Comment by hoisie** [comment]
I'd also like to mention that I am planning to work on using real native Android code for resources, which should greatly reduce the amount of memory required to inflate view. This is going to be a complex project, however, so it won't be done too soon. The binary format of Android resources are designed to be mmap'd for fast lookup, but we are not taking advantage of that, and instead reimplementing everything as a series of Java maps, which is seriously inefficient.

**Comment by barney2k7** [comment]
@hoisie Thank you for your feedback. In fact, `ActivityCompatStressTest` does crash with `OutOfMemoryError` when running with xmx 512m after around 21k iterations (roughly 9 minutes). I've updated the 'steps to reproduce' accordingly.

**Comment by hoisie** [comment]
@barney2k7 thanks for this investigation, I can reproduce the `OutOfMemoryError`. However, because it is happening after so many iterations, I do not believe the theme-related objects are leaking. If they were, the `OutOfMemoryError` would happen much sooner, perhaps after dozens of iterations. 

 I think there are some memory leaks occurring, but they are slower leaks.

I added `jvmArgs '-XX:+HeapDumpOnOutOfMemoryError'`, and this is what I am seeing:

<img width="1059" alt="image" src="https://github.com/robolectric/robolectric/assets/125547/e2fda81e-a24d-440d-a551-181b37e1b4be">

There are some suspicious things, like the ShadowVectorDrawable objects. Perhaps there is a slow leak that eventually consumes enough memory and causes an OutOfMemoryError.

**Comment by hoisie** [comment]
@barney2k7 I noticed a legitimate (and fairly serious) leak in ShadowVMRuntime that was leaking int[] objects. Not sure how this slipped under our radar for so long, yikes. With that fix the test can create and destroy 50k ActivityCompat objects with `maxHeapSize = "512m"`.

However, even with that fix, I suspect that there may be additional (and perhaps more serious) leaks in your tests if you are seeing OOMs. If you add `jvmArgs '-XX:+HeapDumpOnOutOfMemoryError'` to your tests and get an hprof, I'd be happy to take a look at it if you'd like to share it with me via Google Drive.

**Comment by barney2k7** [comment]
@hoisie thanks to your input above
> If you are seeing OutOfMemoryErrors, the first thing I would check is for any Activity/Fragment/View objects that leak across tests. You can do this by just searching for `Activity` in visualVM. Typically there should be a very small number. The `CppAssetManager$Theme` objects are the result of View inflation, which happens when Activities and Fragments are created. These `CppAssetManager$Theme` are only freed when the underlying Activities are GC'd. If you are seeing a lot of Activity objects in VisualVM, trace the path to roots and see if something is preventing Activity objects from being collected.

I was able to tackle the remaining memory leaks in my test suite. There were in fact some activitiy objects leaking due to mockito and also some application objects due to them being hooked into `Thread.setDefaultUncaughtExceptionHandler` and/or `ProcessLifecycleOwner`.
As you already extracted (and fixed) the actual memory leak in robolectric I've reproduced into #8428, I'm closing this issue here.
Thanks again for your support, and I'm happy to actually have uncovered a memory leak in robolectric after all :smiley:
