### ISSUE TITLE
Flakiness with 

### ISSUE THREAD

**Issue by saket** [robolectric/robolectric#8551]
### Description
I'm observing some flakiness during creation of in-memory database in my robolectric tests. I don't have anything to share other than the stacktrace because the crash isn't 100% reproducible:

```kotlin
java.sql.SQLException: No suitable driver found for jdbc:sqlite:
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:706)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:190)
	at app.cash.sqldelight.driver.jdbc.sqlite.InMemoryConnectionManager.<init>(JdbcSqliteDriver.kt:76)
	at app.cash.sqldelight.driver.jdbc.sqlite.JdbcSqliteDriverKt.connectionManager(JdbcSqliteDriver.kt:54)
	at app.cash.sqldelight.driver.jdbc.sqlite.JdbcSqliteDriverKt.access$connectionManager(JdbcSqliteDriver.kt:1)
	at app.cash.sqldelight.driver.jdbc.sqlite.JdbcSqliteDriver.<init>(JdbcSqliteDriver.kt:21)
	at app.cash.sqldelight.driver.jdbc.sqlite.JdbcSqliteDriver.<init>(JdbcSqliteDriver.kt:14)
```

I've never seen this crash before in my non-robolectric tests so I wonder if this is related to robolectric?

### Steps to Reproduce

I'm using SQLDelight's `JdbcSqliteDriver` but I'm assuming that calling `DriverManager.getConnection("jdbc:sqlite:")` is sufficient to trigger the crash.

```kotlin
JdbcSqliteDriver(JdbcSqliteDriver.IN_MEMORY)
```

```groovy
testImplementation "app.cash.sqldelight:sqlite-driver:2.0.0"
```

### Robolectric Version
4.10.3

**Comment by hoisie** [comment]
The first step when dealing with test flakiness is to determine the sources of nondeterminism that affect the test. Because this doesn't happen 100% of the time, I would recommend introducing logging to print important events during the course of a test. And then run the tests multiple times to figure out the sources of nondeterminism. Because this is SQL-related, I would check for things like SQL connections leaking to subsequent tests (test pollution), or race conditions due to SQLite being initialized on separate background threads.

Once you have identified the sources of nondeterminism, and you still believe this is a Robolectric issue, please post here with details and re-open the issue.

In a Robolectric environment you are essentially using the real Android SQLite code, so there's not really much Robolectric is doing that is different from real Android.

**Comment by saket** [comment]
> Because this is SQL-related, I would check for things like SQL connections leaking to subsequent tests (test pollution), or race conditions due to SQLite being initialized on separate background threads.

I don't think this is the case because this 100% does not happen when robolectric isn't used, so I'm certain that robolectric is the source of the problem somewhere. 

If anyone else is reading this, I ended up initializing my `JdbcSqliteDriver` in a loop until it succeeds because I wasn't able to find time to investigate the source of nondeterminism.
