### ISSUE TITLE
nativegraphics tests failed on master's CI after 20240110 merging from google3

### ISSUE THREAD

**Issue by utzcoz** [robolectric/robolectric#8736]
See https://github.com/robolectric/robolectric/actions/runs/7451456865/job/20329007366.

Looks like it is not flaky because they still fail after I re-triggerred it. cc @hoisie .

**Comment by hoisie** [comment]
Looks like a memory issue:

`Caused by: org.gradle.process.internal.ExecException: Process 'Gradle Test Executor 4' finished with non-zero exit value 134`

I vaguely remember error 134 is when the container is killed due to excessive memory usage.

**Comment by hoisie** [comment]
My hunch is that it's related to the preinstrumented jars being switched off... I can try to turn them back on.

**Comment by hoisie** [comment]
It doesn't actually seem to be related to preinstrumented jars. I'll try to set up a git bisect and see what is happening.

**Comment by takahirom** [comment]
I suspected that Roborazzi might be causing the issue, so I conducted a check. 
Is it possible that the issue is linked to these specific commits?
CI Passed: https://github.com/robolectric/robolectric/commit/5043dab072ec2c9dcf5de01e4db4a3d2d89cba16
CI Failed: https://github.com/robolectric/robolectric/commit/9ce906d6ec23804fb89ab1c10edfee5970f41327
Comparison 
 https://github.com/robolectric/robolectric/compare/5043dab072ec2c9dcf5de01e4db4a3d2d89cba16...9ce906d6ec23804fb89ab1c10edfee5970f41327

**Comment by hoisie** [comment]
@takahirom thanks for taking a look. Weird, most of those diff should be more or less no-ops.

**Comment by hoisie** [comment]
@takahirom nice catch! It does seem to be caused by 0f9b489bf4e10912cafa106027d969e4d22bdd34. I did add another test for ShadowNativeAllocationRegistry, and there is a stress test here:

https://github.com/robolectric/robolectric/blob/master/integration_tests/nativegraphics/src/test/java/org/robolectric/integrationtests/nativegraphics/ShadowNativeAllocationRegistryTest.java#L34-L44

Maybe adding the minSdk=O at the class level caused it to be run more than once? I thought it would still only be run once...

**Comment by hoisie** [comment]
I sent https://github.com/robolectric/robolectric/pull/8739 to remove a problematic stress test. Perhaps the issue was the the process was near OOM already and something tipped it over the edge.

FYI that stress test will continue to run on Google's infrastructure, but it does not play nicely with GitHub CI.

**Comment by hoisie** [comment]
Actually, maybe the problem is [applyFreeFunction_matrix](https://github.com/robolectric/robolectric/blob/master/integration_tests/nativegraphics/src/test/java/org/robolectric/integrationtests/nativegraphics/ShadowNativeAllocationRegistryTest.java#L31).

Perhaps there is a native crash happening? I wonder if zero'ing the pointer is causing a segfault.

**Comment by hoisie** [comment]
I believe that [applyFreeFunction_matrix](https://github.com/robolectric/robolectric/blob/master/integration_tests/nativegraphics/src/test/java/org/robolectric/integrationtests/nativegraphics/ShadowNativeAllocationRegistryTest.java#L31) has a double-free issue. I call applyFreeFunction directly, which frees it once in native code, and then when it is GC's it wil be freed again in native code.

This does not happen in Bazel/Blaze because each test is run in a separate process, so maybe GC does not need to occur.

I will avoid calling applyFreeFunction directly.

**Comment by hoisie** [comment]
This should be fixed by https://github.com/robolectric/robolectric/pull/8739.
